// fsd-v2/frontend/src/components/Modal.tsx
import { ReactNode, useEffect, useId, useRef } from 'react';
import { X } from 'lucide-react';

interface Props {
  title: string;
  onClose: () => void;
  children: ReactNode;
  footer?: ReactNode;
}

// Selector for the elements that can hold keyboard focus inside the dialog.
const FOCUSABLE =
  'a[href], button:not([disabled]), textarea:not([disabled]), input:not([disabled]), select:not([disabled]), [tabindex]:not([tabindex="-1"])';

// Accessible overlay modal: labelled dialog with a focus trap. Escape and
// backdrop-click close; content clicks are swallowed so a click inside a form
// doesn't dismiss it. On open we move focus into the dialog and trap Tab
// inside it; on close we restore focus to whatever was focused before, so
// keyboard and screen-reader users never end up stranded behind the modal
// (previously Tab walked straight out into the page underneath).
export function Modal({ title, onClose, children, footer }: Props) {
  const dialogRef = useRef<HTMLDivElement>(null);
  const titleId = useId();

  useEffect(() => {
    // Remember the trigger so we can hand focus back when the modal closes.
    const previouslyFocused = document.activeElement as HTMLElement | null;

    // Move focus into the dialog: first focusable element, else the dialog
    // container (which is tabindex=-1 so it can receive programmatic focus).
    const dialog = dialogRef.current;
    const first = dialog?.querySelector<HTMLElement>(FOCUSABLE);
    (first ?? dialog)?.focus();

    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') { onClose(); return; }
      if (e.key !== 'Tab' || !dialog) return;
      const focusables = Array.from(dialog.querySelectorAll<HTMLElement>(FOCUSABLE))
        .filter((el) => el.offsetParent !== null || el === document.activeElement);
      if (focusables.length === 0) { e.preventDefault(); return; }
      const firstEl = focusables[0];
      const lastEl = focusables[focusables.length - 1];
      const active = document.activeElement as HTMLElement | null;
      // Wrap around the ends so Tab/Shift+Tab can never escape the dialog.
      if (e.shiftKey && (active === firstEl || !dialog.contains(active))) {
        e.preventDefault(); lastEl.focus();
      } else if (!e.shiftKey && active === lastEl) {
        e.preventDefault(); firstEl.focus();
      }
    };
    document.addEventListener('keydown', onKey);
    return () => {
      document.removeEventListener('keydown', onKey);
      // Restore focus to the trigger element on unmount.
      previouslyFocused?.focus?.();
    };
  }, [onClose]);

  return (
    <div className="modal-backdrop" onClick={onClose}>
      <div
        className="modal"
        ref={dialogRef}
        role="dialog"
        aria-modal="true"
        aria-labelledby={titleId}
        tabIndex={-1}
        onClick={(e) => e.stopPropagation()}
      >
        <header>
          <h3 id={titleId}>{title}</h3>
          <button className="iconbtn" onClick={onClose} aria-label="close"><X size={16}/></button>
        </header>
        <section>{children}</section>
        {footer && <footer>{footer}</footer>}
      </div>
    </div>
  );
}

// src/presentation/web/spa/src/components/Modal.vue
<template>
  <Teleport to="body">
    <div class="overlay" @click.self="$emit('close')" role="presentation">
      <div
        ref="dialogEl"
        class="modal"
        role="dialog"
        aria-modal="true"
        :aria-labelledby="titleId"
        tabindex="-1"
        @keydown="onKey"
      >
        <header v-if="title || $slots.header">
          <h3 :id="titleId">
            <slot name="header">{{ title }}</slot>
          </h3>
          <button
            class="icon-btn"
            type="button"
            :aria-label="$t('common.close')"
            @click="$emit('close')"
          >
            <X :size="18" aria-hidden="true" />
          </button>
        </header>
        <section><slot /></section>
        <footer v-if="$slots.footer">
          <slot name="footer" />
        </footer>
      </div>
    </div>
  </Teleport>
</template>

<script setup>
import { onMounted, onBeforeUnmount, nextTick, ref } from 'vue'
import { X } from 'lucide-vue-next'

defineProps({ title: { type: String, default: '' } })
const emit = defineEmits(['close'])
const titleId = `dlg-${Math.random().toString(36).slice(2, 9)}`
const dialogEl = ref(null)

// Element that had focus before the modal opened, so we can return focus
// when it closes (WCAG 2.4.3 Focus Order, 2.4.7 Focus Visible).
let lastFocused = null

const focusableSelector = [
  'a[href]',
  'button:not([disabled])',
  'textarea:not([disabled])',
  'input:not([disabled]):not([type="hidden"])',
  'select:not([disabled])',
  '[tabindex]:not([tabindex="-1"])',
].join(',')

function focusables() {
  if (!dialogEl.value) return []
  return Array.from(dialogEl.value.querySelectorAll(focusableSelector)).filter(
    (el) => !el.hasAttribute('aria-hidden')
  )
}

// Keep tab within the modal — pressing Tab from the last element cycles
// back to the first, and Shift+Tab from the first jumps to the last.
function onKey(e) {
  if (e.key === 'Escape') {
    emit('close')
    return
  }
  if (e.key !== 'Tab') return
  const els = focusables()
  if (els.length === 0) {
    e.preventDefault()
    dialogEl.value?.focus()
    return
  }
  const first = els[0]
  const last = els[els.length - 1]
  const active = document.activeElement
  if (e.shiftKey && active === first) {
    e.preventDefault()
    last.focus()
  } else if (!e.shiftKey && active === last) {
    e.preventDefault()
    first.focus()
  }
}

onMounted(async () => {
  lastFocused = document.activeElement
  await nextTick()
  const els = focusables()
  ;(els[0] || dialogEl.value)?.focus()
})

onBeforeUnmount(() => {
  // Restore focus to the trigger so keyboard users don't get teleported
  // to the document body. Guard against the trigger being unmounted.
  if (lastFocused && typeof lastFocused.focus === 'function') {
    lastFocused.focus()
  }
})
</script>
