// fsd-v2/frontend/src/components/ResourceEditor.tsx
import { useEffect, useMemo, useState } from 'react';
import { Plus, Trash2, Save, X, Combine } from 'lucide-react';
import { Modal } from './Modal';
import { Switch } from './Switch';
import { api } from '../api/client';
import { useToast } from '../stores/toast';

interface Resource {
  id?: string;
  name?: string;
  location?: string;
  region?: string;
  assetType?: string;
  capacity?: number;
  isActive?: boolean;
  isRestricted?: boolean;
  requiresApproval?: boolean;
  bookingMode?: 'exclusive' | 'shared';
  sharedCapacity?: number;
  departmentId?: string | null;
  equipment?: string[];
  compositeMode?: 'parent' | 'child' | '';
  subResources?: SubResource[];
  customFields?: CustomField[];
}

interface SubResource { name: string; capacity: number; }
interface CustomField { key: string; label: string; type: 'text' | 'number' | 'select' | 'date' | 'checkbox'; required?: boolean; options?: string[]; }

interface Props {
  resource: Resource;
  departments?: { id: string; name: string }[];
  onClose: () => void;
  onSaved?: () => void;
}

// Full resource edit dialog — replaces the 6-field inline form that
// used to live inside pages/AdminResources.tsx. Covers the basic info,
// the booking-mode (exclusive / shared / pods) selector, sub-resource
// hierarchy and a custom-fields editor so admins can tailor the booking
// flow per room. Port of v1's ResourceEditor.vue, simplified to drop
// the floor-plan position editor (still owned by the floor-plan view).
const REGIONS = ['Hong Kong', 'Kowloon', 'New Territories'];
const ASSET_TYPES = ['Meeting Room', 'Conference', 'Top Management', 'Equipment', 'Vehicle'];
const FIELD_TYPES: CustomField['type'][] = ['text', 'number', 'select', 'date', 'checkbox'];

export function ResourceEditor({ resource, departments = [], onClose, onSaved }: Props) {
  const toast = useToast();
  const [form, setForm] = useState<Resource>(() => ({
    bookingMode: 'exclusive',
    sharedCapacity: 1,
    isActive: true,
    subResources: [],
    customFields: [],
    equipment: [],
    ...resource,
  }));
  const [busy, setBusy] = useState(false);

  // Sub-resource hierarchy mode: whole (standalone), splittable (parent
  // with N child rooms), or pods (one resource bookable by N people).
  type Mode = 'whole' | 'splittable' | 'pods';
  const initialMode: Mode =
    form.bookingMode === 'shared' ? 'pods'
    : (form.compositeMode === 'parent' || (form.subResources?.length ?? 0) > 0) ? 'splittable'
    : 'whole';
  const [mode, setMode] = useState<Mode>(initialMode);

  useEffect(() => {
    if (mode === 'pods') {
      patch({ bookingMode: 'shared', sharedCapacity: form.sharedCapacity || form.capacity || 2 });
    } else {
      patch({ bookingMode: 'exclusive' });
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [mode]);

  function patch(p: Partial<Resource>) { setForm((f) => ({ ...f, ...p })); }

  function addSub() {
    const next: SubResource = {
      name: `${form.name || 'Sub-resource'} ${((form.subResources?.length ?? 0) + 1)}`,
      capacity: form.capacity || 4,
    };
    patch({ subResources: [...(form.subResources || []), next] });
  }
  function removeSub(i: number) {
    patch({ subResources: (form.subResources || []).filter((_, idx) => idx !== i) });
  }
  function updateSub(i: number, p: Partial<SubResource>) {
    patch({ subResources: (form.subResources || []).map((s, idx) => idx === i ? { ...s, ...p } : s) });
  }

  function addField() {
    const next: CustomField = { key: `field_${(form.customFields?.length ?? 0) + 1}`, label: '', type: 'text' };
    patch({ customFields: [...(form.customFields || []), next] });
  }
  function removeField(i: number) {
    patch({ customFields: (form.customFields || []).filter((_, idx) => idx !== i) });
  }
  function updateField(i: number, p: Partial<CustomField>) {
    patch({ customFields: (form.customFields || []).map((f, idx) => idx === i ? { ...f, ...p } : f) });
  }

  const equipmentStr = useMemo(() => (form.equipment || []).join(', '), [form.equipment]);

  async function save() {
    // Fall back to region for location when blank — mirrors v1 so the
    // server-side equality filter never drops the row.
    if (!form.location || !form.location.trim()) form.location = form.region || '';
    if (!form.name?.trim()) { toast.warning('Name is required'); return; }
    setBusy(true);
    try {
      if (form.id) await api.updateResource(form.id, form);
      else         await api.createResource(form);
      toast.success('Resource saved');
      onSaved?.();
      onClose();
    } catch (e: any) {
      toast.error('Save failed', e.displayMessage || e.message);
    } finally { setBusy(false); }
  }

  async function deactivate() {
    if (!form.id) return;
    if (!confirm(`Deactivate ${form.name}?`)) return;
    setBusy(true);
    try {
      await api.deleteResource(form.id);
      toast.success('Resource deactivated');
      onSaved?.();
      onClose();
    } catch (e: any) {
      toast.error('Delete failed', e.displayMessage || e.message);
    } finally { setBusy(false); }
  }

  return (
    <Modal
      title={form.id ? `Edit ${form.name || 'resource'}` : 'Create resource'}
      onClose={onClose}
      footer={<>
        {form.id && <button className="btn danger" disabled={busy} onClick={deactivate}>
          <Trash2 size={13} /> Deactivate
        </button>}
        <span className="spacer" />
        <button className="btn ghost" onClick={onClose}>Cancel</button>
        <button className="btn primary" disabled={busy} onClick={save}>
          <Save size={13} /> Save
        </button>
      </>}
    >
      <div className="grid-2">
        <label>Name
          <input value={form.name || ''} onChange={(e) => patch({ name: e.target.value })} />
        </label>
        <label>Asset type
          <select value={form.assetType || 'Meeting Room'} onChange={(e) => patch({ assetType: e.target.value })}>
            {ASSET_TYPES.map((t) => <option key={t}>{t}</option>)}
          </select>
        </label>
        <label>Region *
          <select value={form.region || ''} onChange={(e) => patch({ region: e.target.value })}>
            <option value="">—</option>
            {REGIONS.map((r) => <option key={r}>{r}</option>)}
          </select>
        </label>
        <label>Location
          <input value={form.location || ''} onChange={(e) => patch({ location: e.target.value })}
                 placeholder="Building / floor (defaults to region)" />
        </label>
        <label>Capacity
          <input type="number" min={1} value={form.capacity || 1}
                 onChange={(e) => patch({ capacity: +e.target.value })} />
        </label>
        <label>Department
          <select value={form.departmentId || ''}
                  onChange={(e) => patch({ departmentId: e.target.value || null })}>
            <option value="">—</option>
            {departments.map((d) => <option key={d.id} value={d.id}>{d.name}</option>)}
          </select>
        </label>
      </div>

      <label>Equipment (comma separated)
        <input value={equipmentStr}
               onChange={(e) => patch({ equipment: e.target.value.split(',').map((s) => s.trim()).filter(Boolean) })}
               placeholder="Projector, whiteboard, video conf …" />
      </label>

      <div className="row gap mt" style={{ flexWrap: 'wrap' }}>
        <label className="row"><input type="checkbox" checked={!!form.requiresApproval}
          onChange={(e) => patch({ requiresApproval: e.target.checked })} /> Requires approval</label>
        <label className="row"><input type="checkbox" checked={!!form.isRestricted}
          onChange={(e) => patch({ isRestricted: e.target.checked })} /> Restricted</label>
        <label className="row"><input type="checkbox" checked={!!form.isActive}
          onChange={(e) => patch({ isActive: e.target.checked })} /> Active</label>
      </div>

      <div className="bm-box mt">
        <h4 style={{ margin: '0 0 6px' }}><Combine size={14} /> Booking model</h4>
        <p className="muted small">How is this space booked?</p>
        <div className="row gap" style={{ flexWrap: 'wrap' }}>
          <label className="row"><input type="radio" name="rmode" checked={mode === 'whole'} onChange={() => setMode('whole')} /> Whole only</label>
          <label className="row"><input type="radio" name="rmode" checked={mode === 'splittable'} onChange={() => setMode('splittable')} /> Splittable (sub-rooms)</label>
          <label className="row"><input type="radio" name="rmode" checked={mode === 'pods'} onChange={() => setMode('pods')} /> Pods (shared capacity)</label>
        </div>

        {mode === 'pods' && (
          <label className="mt">Concurrent capacity (pods)
            <input type="number" min={1} value={form.sharedCapacity || 1}
                   onChange={(e) => patch({ sharedCapacity: +e.target.value })} />
            <small className="muted">Up to this many independent bookings may overlap.</small>
          </label>
        )}

        {mode === 'splittable' && (
          <div className="mt">
            <div className="row" style={{ justifyContent: 'space-between', alignItems: 'center' }}>
              <b>Sub-resources</b>
              <button type="button" className="btn ghost" onClick={addSub}>
                <Plus size={12} /> Add sub-resource
              </button>
            </div>
            {(form.subResources || []).length === 0 && (
              <p className="muted small">No sub-resources yet — add one to split this space.</p>
            )}
            {(form.subResources || []).map((sub, i) => (
              <div key={i} className="sub-card">
                <div className="row" style={{ justifyContent: 'space-between' }}>
                  <b>Sub-resource {i + 1}</b>
                  <button type="button" className="btn ghost danger" onClick={() => removeSub(i)}>
                    <X size={12} />
                  </button>
                </div>
                <div className="grid-2">
                  <label>Name
                    <input value={sub.name} onChange={(e) => updateSub(i, { name: e.target.value })} />
                  </label>
                  <label>Capacity
                    <input type="number" min={1} value={sub.capacity}
                           onChange={(e) => updateSub(i, { capacity: +e.target.value })} />
                  </label>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      <div className="bm-box mt">
        <div className="row" style={{ justifyContent: 'space-between', alignItems: 'center' }}>
          <div>
            <h4 style={{ margin: 0 }}>Custom fields</h4>
            <p className="muted small">Extra questions asked when booking this resource.</p>
          </div>
          <button type="button" className="btn ghost" onClick={addField}>
            <Plus size={12} /> Add field
          </button>
        </div>
        {(form.customFields || []).map((f, i) => (
          <div key={i} className="sub-card">
            <div className="row" style={{ justifyContent: 'space-between' }}>
              <b>Field {i + 1}</b>
              <button type="button" className="btn ghost danger" onClick={() => removeField(i)}>
                <X size={12} />
              </button>
            </div>
            <div className="grid-2">
              <label>Key
                <input value={f.key} onChange={(e) => updateField(i, { key: e.target.value })} />
              </label>
              <label>Label
                <input value={f.label} onChange={(e) => updateField(i, { label: e.target.value })} />
              </label>
              <label>Type
                <select value={f.type} onChange={(e) => updateField(i, { type: e.target.value as CustomField['type'] })}>
                  {FIELD_TYPES.map((t) => <option key={t}>{t}</option>)}
                </select>
              </label>
              <label className="row" style={{ alignItems: 'center' }}>
                <Switch checked={!!f.required} onChange={(v) => updateField(i, { required: v })} />
                <span style={{ marginLeft: 6 }}>Required</span>
              </label>
            </div>
            {f.type === 'select' && (
              <label>Options (comma separated)
                <input value={(f.options || []).join(', ')}
                       onChange={(e) => updateField(i, { options: e.target.value.split(',').map((s) => s.trim()).filter(Boolean) })} />
              </label>
            )}
          </div>
        ))}
      </div>
    </Modal>
  );
}

// src/presentation/web/spa/src/components/ResourceEditor.vue
<template>
  <Modal @close="$emit('close')" :title="resource.ID ? $t('admin.resources.edit') : $t('admin.resources.create')">
    <div class="grid-2">
      <label class="field"><span>{{ $t('admin.resources.name') }}</span><input v-model="form.Name" /></label>
      <label class="field">
        <span>{{ $t('admin.resources.type') }}</span>
        <select v-model="form.AssetType" @change="applyTypeDefaults">
          <option v-for="t in resourceTypes" :key="t.Key" :value="t.Key">{{ t.Label }}</option>
        </select>
      </label>
      <label class="field">
        <span>{{ $t('admin.resources.region') }}</span>
        <select v-model="form.Region">
          <option>Hong Kong</option><option>Kowloon</option><option>New Territories</option>
        </select>
      </label>
      <label class="field"><span>{{ $t('admin.resources.location') }}</span><input v-model="form.Location" /></label>
      <label class="field"><span>{{ $t('admin.resources.capacity') }}</span><input type="number" v-model.number="form.Capacity" min="1" /></label>
      <label class="field">
        <span>{{ $t('admin.resources.department') }}</span>
        <select v-model="form.DepartmentID">
          <option value="">—</option>
          <option v-for="d in departments" :key="d.ID" :value="d.ID">{{ d.Name }}</option>
        </select>
      </label>
    </div>

    <label class="field mt">
      <span>{{ $t('admin.resources.equipment') }}</span>
      <input :value="(form.Equipment || []).join(', ')"
             @input="form.Equipment = $event.target.value.split(',').map(s => s.trim()).filter(Boolean)"
             :placeholder="$t('admin.resources.equipmentPh')" />
    </label>

    <div class="row gap mt">
      <label class="toggle"><input type="checkbox" v-model="form.RequiresApproval"/> <span>{{ $t('admin.resources.requiresApproval') }}</span></label>
      <label class="toggle"><input type="checkbox" v-model="form.IsRestricted"/>     <span>{{ $t('admin.resources.restricted') }}</span></label>
      <label class="toggle"><input type="checkbox" v-model="form.IsActive"/>          <span>{{ $t('admin.resources.active') }}</span></label>
    </div>

    <!-- Booking mode block — gym/classroom shared bookings -->
    <div class="card mt-lg" style="background: var(--surface-inset); border: 1px dashed var(--border);">
      <h4 style="margin:0 0 6px;"><Users :size="14"/> {{ $t('admin.resources.bookingMode') }}</h4>
      <p class="muted text-sm" style="max-width:560px; margin:0 0 10px;">{{ $t('admin.resources.bookingModeHelp') }}</p>
      <div class="row gap">
        <label class="toggle">
          <input type="radio" name="bmode" value="exclusive" v-model="form.BookingMode"/>
          <span>{{ $t('admin.resources.modeExclusive') }}</span>
        </label>
        <label class="toggle">
          <input type="radio" name="bmode" value="shared" v-model="form.BookingMode"/>
          <span>{{ $t('admin.resources.modeShared') }}</span>
        </label>
      </div>
      <label v-if="form.BookingMode === 'shared'" class="field mt">
        <span>{{ $t('admin.resources.sharedCapacity') }}</span>
        <input type="number" min="2" v-model.number="form.SharedCapacity"/>
        <small class="muted">{{ $t('admin.resources.sharedCapacityHelp') }}</small>
      </label>
    </div>

    <!-- Composite block -->
    <div class="card mt-lg" style="background: var(--surface-inset); border: 1px dashed var(--border);">
      <div class="row" style="justify-content: space-between; align-items: flex-start;">
        <div>
          <h4 style="margin:0 0 4px;"><Combine :size="14"/> {{ $t('admin.resources.compositeTitle') }}</h4>
          <p class="muted text-sm" style="max-width:480px;">{{ $t('admin.resources.compositeHelp') }}</p>
        </div>
        <span class="tag" :class="badge.cls">{{ badge.text }}</span>
      </div>

      <div v-if="form.CompositeMode === 'parent'" class="mt">
        <div class="sub-resources-list">
          <div v-for="(sub, idx) in splitForm.sub_resources" :key="idx" class="sub-resource-item">
            <div class="sub-resource-header">
              <span class="sub-resource-title">{{ $t('admin.resources.subResource') }} {{ idx + 1 }}</span>
              <button class="btn ghost danger sm" @click.prevent="removeSubResource(idx)" v-if="splitForm.sub_resources.length > 1">
                <Trash2 :size="12"/>
              </button>
            </div>
            <div class="grid-2">
              <label class="field">
                <span>{{ $t('admin.resources.name') }}</span>
                <input v-model="sub.name" :placeholder="$t('admin.resources.subResourceNamePh')" />
              </label>
              <label class="field">
                <span>{{ $t('admin.resources.capacity') }}</span>
                <input type="number" v-model.number="sub.capacity" min="1" />
              </label>
            </div>
          </div>
          <button class="btn ghost sm mt" @click.prevent="addSubResource">
            <Plus :size="12"/> {{ $t('admin.resources.addSubResource') }}
          </button>
        </div>
      </div>

      <div v-if="!form.ID && form.CompositeMode !== 'child'" class="mt">
        <button class="btn ghost sm" @click.prevent="showSplit = !showSplit">
          <SplitSquareVertical :size="13"/> {{ $t('admin.resources.splitAction') }}
        </button>
      </div>

      <div v-if="showSplit" class="mt">
        <div class="grid-2">
          <label class="field">
            <span>{{ $t('admin.resources.childCount') }}</span>
            <input type="number" v-model.number="splitForm.child_count" min="2" max="10"/>
          </label>
          <label class="field">
            <span>{{ $t('admin.resources.childCapacity') }}</span>
            <input type="number" v-model.number="splitForm.child_capacity" min="1"/>
          </label>
        </div>
        <label class="field mt">
          <span>{{ $t('admin.resources.childNamesOpt') }}</span>
          <textarea rows="2" :value="(splitForm.child_names || []).join('\n')"
                    @input="splitForm.child_names = $event.target.value.split('\n').map(s => s.trim()).filter(Boolean)"
                    :placeholder="$t('admin.resources.childNamesPh')"></textarea>
        </label>
        <label class="field mt">
          <span>{{ $t('admin.resources.equipment') }}</span>
          <input :value="(splitForm.child_equipment || []).join(', ')"
                 @input="splitForm.child_equipment = $event.target.value.split(',').map(s => s.trim()).filter(Boolean)" />
        </label>
        <button class="btn mt" @click.prevent="doSplit" :disabled="busy">
          <SplitSquareVertical :size="13"/> {{ $t('admin.resources.confirmSplit') }}
        </button>
      </div>
    </div>

    <!-- Operating Hours -->
    <div class="card mt-lg" style="background: var(--surface-inset); border: 1px dashed var(--border);">
      <h4 style="margin:0 0 6px;">Operating Hours</h4>
      <div v-for="day in operatingHours" :key="day.Weekday" class="day-row">
        <span class="day-name">{{ dayName(day.Weekday) }}</span>
        <label class="toggle"><input type="checkbox" v-model="day.IsClosed"/> <span>Closed</span></label>
        <div class="row gap-sm" v-if="!day.IsClosed">
          <input type="time" v-model="day.OpenTime" />
          <span>-</span>
          <input type="time" v-model="day.CloseTime" />
        </div>
      </div>
    </div>

    <template #footer>
      <button class="btn ghost danger" v-if="form.ID" @click="deactivate" :disabled="busy">
        <Trash2 :size="13"/> {{ $t('admin.resources.deactivate') }}
      </button>
      <span class="space"></span>
      <button class="btn ghost" @click="$emit('close')">{{ $t('common.cancel') }}</button>
      <button class="btn" @click="save" :disabled="busy"><Save :size="13"/> {{ $t('common.save') }}</button>
    </template>
  </Modal>
</template>

<style scoped>
.day-row {
  display: grid;
  grid-template-columns: 100px 100px 1fr;
  gap: 16px;
  align-items: center;
  padding: 8px 0;
}
.day-name {
  font-weight: 500;
}

.sub-resources-list {
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.sub-resource-item {
  background: var(--bg-elevated);
  border: 1px solid var(--border);
  border-radius: var(--radius);
  padding: 12px;
}

.sub-resource-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 8px;
}

.sub-resource-title {
  font-weight: 600;
  font-size: 13px;
  color: var(--text);
}
</style>

<script setup>
import { computed, reactive, ref, onMounted } from 'vue'
import { useI18n } from 'vue-i18n'
import { Combine, SplitSquareVertical, Save, Trash2, Users, Plus } from 'lucide-vue-next'
import Modal from './Modal.vue'
import { api } from '../api'
import { useToastStore } from '../stores/toast'

const props = defineProps({ resource: Object, departments: { type: Array, default: () => [] } })
const emit = defineEmits(['close', 'saved', 'split'])

const { t } = useI18n()
const toasts = useToastStore()
// Apply sane defaults so unsaved fields don't post as null/undefined
const form = reactive({
  BookingMode: 'exclusive',
  SharedCapacity: 1,
  ...props.resource
})
const busy = ref(false)
const showSplit = ref(false)
const splitForm = reactive({
  child_count: 3, 
  child_capacity: 4, 
  child_names: [], 
  child_equipment: [],
  sub_resources: []
})

// Initialize sub_resources when composite mode is parent
if (form.CompositeMode === 'parent' && form.SubResourceCount > 0) {
  for (let i = 0; i < form.SubResourceCount; i++) {
    splitForm.sub_resources.push({
      name: form.Name ? `${form.Name} - ${i + 1}` : `Sub-resource ${i + 1}`,
      capacity: Math.floor(form.Capacity / form.SubResourceCount) || 4
    })
  }
}
// Tenant-defined resource types (gym, studio, parking, …). Falls back to the
// 4 built-ins if the catalog endpoint isn't reachable yet.
const resourceTypes = ref([
  { Key: 'Room', Label: 'Meeting room' },
  { Key: 'Vehicle', Label: 'Vehicle' },
  { Key: 'Equipment', Label: 'Equipment' },
  { Key: 'Top Management', Label: 'Senior management' }
])

const operatingHours = ref([])





function dayName(weekday) {
  return ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'][weekday]
}

function createDefaultHours() {
  const hours = []
  for (let i = 0; i < 7; i++) {
    hours.push({
      Weekday: i,
      IsClosed: i === 0 || i === 6,
      OpenTime: '09:00',
      CloseTime: '17:00'
    })
  }
  return hours
}

onMounted(async () => {
  try {
    const list = await api.listResourceTypes()
    if (Array.isArray(list) && list.length) resourceTypes.value = list
  } catch { /* keep fallback */ }
  if (props.resource.ID) {
    try {
      const hours = await api.getOperatingHours(props.resource.ID)
      if (hours && hours.length) {
        operatingHours.value = hours.map(h => ({
          ...h,
          OpenTime: h.OpenTime.slice(0, 5),
          CloseTime: h.CloseTime.slice(0, 5)
        }))
      } else {
        operatingHours.value = createDefaultHours()
      }
    } catch (e) {
      toasts.error('Could not load operating hours', e.message)
      operatingHours.value = createDefaultHours()
    }
  } else {
    operatingHours.value = createDefaultHours()
  }
})

function applyTypeDefaults() {
  const def = resourceTypes.value.find(t => t.Key === form.AssetType)
  if (!def) return
  if (!form.ID) {
    if (def.DefaultCapacity)        form.Capacity = def.DefaultCapacity
    if (def.DefaultBookingMode)     form.BookingMode = def.DefaultBookingMode
    form.RequiresApproval = !!def.DefaultRequiresApproval
    if (def.DefaultBookingMode === 'shared' && !form.SharedCapacity) {
      form.SharedCapacity = def.DefaultCapacity || 10
    }
  }
}

const badge = computed(() => {
  if (form.CompositeMode === 'parent') return { cls: 'brand', text: t('admin.resources.parent') }
  if (form.CompositeMode === 'child')  return { cls: 'info',  text: t('admin.resources.child') }
  return { cls: '', text: t('admin.resources.standalone') }
})

async function save() {
  busy.value = true
  try {
    let resourceId = form.ID
    if (resourceId) {
      await api.updateResource(resourceId, form)
    } else {
      const newResource = await api.createResource(form)
      resourceId = newResource.ID
    }

    const hoursToSave = operatingHours.value.map(h => ({
      ...h,
      ResourceID: resourceId
    }))
    await api.setOperatingHours(resourceId, hoursToSave)

    toasts.success(t('admin.resources.saved'))
    emit('saved')
  } catch (e) { toasts.error('Save failed', e.message) }
  finally { busy.value = false }
}

async function deactivate() {
  if (!confirm(t('admin.resources.confirmDeactivate'))) return
  busy.value = true
  try {
    await api.deactivateResource(form.ID)
    toasts.success(t('admin.resources.deactivated'))
    emit('saved')
  } catch (e) { toasts.error('Failed', e.message) }
  finally { busy.value = false }
}

async function doSplit() {
  if (!form.ID) {
    toasts.warn(t('admin.resources.saveFirst'))
    return
  }
  busy.value = true
  try {
    const res = await api.splitResource(form.ID, splitForm)
    emit('split', res)
  } catch (e) { toasts.error('Split failed', e.message) }
  finally { busy.value = false }
}

function addSubResource() {
  splitForm.sub_resources.push({
    name: `Sub-resource ${splitForm.sub_resources.length + 1}`,
    capacity: form.Capacity || 4
  })
}

function removeSubResource(idx) {
  splitForm.sub_resources.splice(idx, 1)
}
</script>
