// fsd-v2/frontend/src/components/Skeleton.tsx
import { CSSProperties } from 'react';

interface Props {
  width?: string;
  height?: string;
  radius?: string;
  style?: CSSProperties;
}

// Port of v1's Skeleton.vue. Pair with the shimmer keyframe defined in
// index.css (added alongside this component).
export function Skeleton({ width = '100%', height = '14px', radius = '4px', style }: Props) {
  return (
    <div
      className="skeleton"
      aria-hidden="true"
      style={{ width, height, borderRadius: radius, ...style }}
    />
  );
}

// src/presentation/web/spa/src/components/Skeleton.vue
<template>
  <div class="skeleton" :style="style" aria-hidden="true" />
</template>

<script setup>
import { computed } from 'vue'
const props = defineProps({
  width: { type: String, default: '100%' },
  height: { type: String, default: '14px' },
  radius: { type: String, default: 'var(--radius-sm)' }
})
const style = computed(() => ({ width: props.width, height: props.height, borderRadius: props.radius }))
</script>
