// src/presentation/web/spa/src/components/BookingModal.vue
<template>
  <Modal @close="$emit('close')">
    <template #header>
      <div class="row gap-sm">
        <CalendarPlus :size="18" />
        <span>{{ $t('booking.confirm') }}</span>
      </div>
    </template>

    <!-- Summary -->
    <div class="summary">
      <div class="thumb" :style="{ background: 'linear-gradient(135deg, var(--brand-primary), var(--brand-secondary))' }">
        <Building2 :size="20" color="white" />
      </div>
      <div class="space">
        <h3>{{ resource.Name || resource.name }}</h3>
        <small class="muted">{{ resource.Location || resource.location }} · {{ resource.Capacity || resource.capacity }} pax</small>
      </div>
    </div>

    <div class="time-row mt mb-lg">
      <div class="row gap-sm"><Calendar :size="14" /> {{ formatDate(date) }}</div>
      <div class="row gap-sm"><Clock :size="14" /> {{ start }} – {{ end }}</div>
      <span class="tag" :class="needsApproval ? 'warning' : 'success'">
        {{ needsApproval ? $t('search.approval') : $t('booking.autoApproved') }}
      </span>
    </div>

    <!-- Recurrence -->
    <div class="card recurrence mb">
      <label class="toggle">
        <input type="checkbox" v-model="recur"/>
        <span><Repeat :size="13"/> {{ $t('booking.makeRecurring') }}</span>
      </label>
      <div v-if="recur" class="grid-2 mt">
        <label class="field">
          <span>{{ $t('booking.pattern') }}</span>
          <select v-model="pattern">
            <option v-if="allowsPattern('daily')" value="daily">{{ $t('booking.daily') }}</option>
            <option v-if="allowsPattern('weekly')" value="weekly">{{ $t('booking.weekly') }}</option>
            <option v-if="allowsPattern('weekly')" value="bi-weekly">{{ $t('booking.biweekly') }}</option>
            <option v-if="allowsPattern('monthly')" value="monthly">{{ $t('booking.monthly') }}</option>
          </select>
        </label>
        <label class="field">
          <span>{{ $t('booking.occurrences') }}</span>
          <input type="number" v-model.number="count" min="1" max="100"/>
        </label>
      </div>
    </div>

    <!-- Custom fields -->
    <div v-if="customFields.length">
      <label class="field" v-for="f in customFields" :key="f.key">
        <span>{{ f.label?.[locale] || f.label?.en || f.key }}{{ f.required ? ' *' : '' }}</span>
        <select v-if="f.type === 'select'" v-model="customData[f.key]">
          <option disabled value="">—</option>
          <option v-for="o in f.options" :key="o" :value="o">{{ o }}</option>
        </select>
        <input v-else-if="f.type === 'number'" type="number" v-model.number="customData[f.key]" />
        <input v-else-if="f.type === 'date'" type="date" v-model="customData[f.key]" />
        <label v-else-if="f.type === 'checkbox'" class="toggle" style="margin-top:4px;">
          <input type="checkbox" v-model="customData[f.key]" />
          <span>{{ f.label?.[locale] || f.key }}</span>
        </label>
        <input v-else type="text" v-model="customData[f.key]" />
      </label>
    </div>

    <label class="field">
      <span>{{ $t('booking.title') }} <span v-if="true">*</span></span>
      <input v-model="title" placeholder="e.g. Weekly Team Sync" required />
    </label>

    <label class="field">
      <span>{{ $t('booking.meetingURL') }}</span>
      <input v-model="meetingURL" placeholder="https://teams.microsoft.com/…" />
    </label>

    <!-- Outlook-style "Private appointment" flag. When checked, only
         the owner and System Admin see organiser / subject; everyone
         else sees "Reserved" on calendars. Useful for VIP meetings on
         otherwise-public rooms. -->
    <label class="toggle mt">
      <input type="checkbox" v-model="isPrivate" />
      <span>
        <Lock :size="13" />
        {{ $t('booking.markPrivate') }}
      </span>
    </label>
    <small class="muted" style="display:block; margin-left:24px; margin-top:-4px;">
      {{ $t('booking.markPrivateHelp') }}
    </small>

    <!-- Result panel -->
    <div v-if="result" class="result mt">
      <div class="row gap" style="align-items: flex-start;">
        <div class="result-icon" :class="result.requires_approval ? 'pending' : 'ok'">
          <Clock v-if="result.requires_approval" :size="16" />
          <Check v-else :size="16" />
        </div>
        <div class="space">
          <b>{{ result.requires_approval ? $t('booking.pending') : $t('booking.success') }}</b>
          <p class="muted text-sm">{{ result.requires_approval ? $t('booking.pendingDesc') : $t('booking.successDesc') }}</p>
        </div>
      </div>

      <div v-if="result.checkin_token" class="qr-block mt">
        <canvas ref="qrCanvas" />
        <div class="text-sm muted" style="text-align: center; margin-top: 8px;">
          {{ $t('booking.qr') }}
        </div>
      </div>
    </div>

    <div v-if="ruleError" class="banner danger" style="margin-top:12px;">
      <span>{{ ruleError }}</span>
    </div>

    <template #footer>
      <button class="btn ghost" @click="$emit('close')">{{ $t('booking.cancel') }}</button>
      <button class="btn" :disabled="busy || !!result || !!ruleError" @click="submit">
        <Loader2 v-if="busy" :size="14" class="spin" />
        {{ $t('booking.submit') }}
      </button>
    </template>
  </Modal>
</template>

<script setup>
import { computed, nextTick, reactive, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import QRCode from 'qrcode'
import { Building2, Calendar, Clock, Check, CalendarPlus, Loader2, Repeat, Lock } from 'lucide-vue-next'
import Modal from './Modal.vue'
import { api } from '../api'
import { useTenantStore } from '../stores/tenant'
import { useToastStore } from '../stores/toast'
import { useBookingRules } from '../composables/bookingRules'

const props = defineProps(['resource', 'date', 'start', 'end'])
const emit = defineEmits(['close', 'booked'])

const tenant = useTenantStore()
const toasts = useToastStore()
const { locale } = useI18n()
const { validate: validateRules, allowsPattern } = useBookingRules()

// Admin-configured booking constraints (min/max duration, horizon, …).
const ruleError = computed(() => validateRules({ date: props.date, start: props.start, end: props.end }))
const customFields = computed(() => tenant.customization?.custom_fields || [])
const customData = reactive({})
const title = ref('')
const meetingURL = ref('')
// Outlook-style "Private appointment" toggle — strips PII for non-owners
// even when the resource ACL would otherwise allow it.
const isPrivate = ref(false)
const busy = ref(false)
const result = ref(null)
const qrCanvas = ref(null)

const recur = ref(false)
const pattern = ref('weekly')
const count = ref(4)

const needsApproval = computed(() => props.resource.RequiresApproval || props.resource.requires_approval)

function formatDate(d) {
  if (!d) return ''
  return new Date(d + 'T00:00:00').toLocaleDateString(locale.value, { weekday: 'long', month: 'short', day: 'numeric' })
}

async function submit() {
  if (ruleError.value) { toasts.error('Cannot book', ruleError.value); return }
  busy.value = true
  try {
    // Convert local date+time to proper ISO with timezone offset
    const startLocal = new Date(`${props.date}T${props.start}:00`)
    const endLocal = new Date(`${props.date}T${props.end}:00`)
    const r = await api.createBooking({
      resource_id: props.resource.ID || props.resource.id,
      start_time: startLocal.toISOString(),
      end_time: endLocal.toISOString(),
      title: title.value || undefined,
      meeting_url: meetingURL.value || undefined,
      is_private: isPrivate.value,
      custom_data: customData,
      recurrence: recur.value ? { pattern: pattern.value, count: count.value } : undefined
    })
    result.value = r || { status: 'Confirmed' }
    if (result.value.checkin_token) {
      await nextTick()
      QRCode.toCanvas(qrCanvas.value, location.origin + '/api/v1/checkin/' + result.value.checkin_token, { width: 200, margin: 1 })
    }
    setTimeout(() => emit('booked'), 1600)
  } catch (e) {
    toasts.error('Booking failed', e.message)
  } finally { busy.value = false }
}
</script>

<style scoped>
.summary { display: flex; gap: 14px; align-items: center; }
.thumb { width: 48px; height: 48px; border-radius: 12px; display: grid; place-items: center; }

.time-row {
  display: flex; gap: 14px; flex-wrap: wrap;
  padding: 10px 12px;
  background: var(--surface-inset);
  border-radius: var(--radius-sm);
  font-size: 13px; color: var(--text-secondary);
}

.recurrence { background: var(--surface-inset); border: 1px dashed var(--border); }

.result {
  padding: 16px; border-radius: var(--radius);
  background: var(--surface-inset);
  border: 1px solid var(--border);
}
.result-icon {
  width: 32px; height: 32px; border-radius: 50%;
  display: grid; place-items: center;
  background: var(--success-bg); color: var(--success); flex-shrink: 0;
}
.result-icon.pending { background: var(--warning-bg); color: var(--warning); }

.qr-block { padding: 16px; background: white; border-radius: var(--radius-sm); display: grid; place-items: center; }
.spin { animation: spin 1s linear infinite; }
@keyframes spin { to { transform: rotate(360deg); } }
</style>

// fsd-v2/frontend/src/components/BookingModal.tsx
import { useMemo, useState } from 'react';
import { Building2, Calendar, Clock, Check, Loader2, Repeat, Lock } from 'lucide-react';
import { Modal } from './Modal';
import { Switch } from './Switch';
import { api } from '../api/client';
import { useToast } from '../stores/toast';
import { useBookingRules } from '../hooks/useBookingRules';

interface Resource {
  id?: string;
  ID?: string;
  name?: string;
  Name?: string;
  location?: string;
  Location?: string;
  capacity?: number;
  Capacity?: number;
  requiresApproval?: boolean;
  RequiresApproval?: boolean;
}

interface Props {
  resource?: Resource;       // pre-selected room (optional — Teams-style: pick inside the dialog)
  resources?: Resource[];    // full list to choose from when no room is pre-selected
  date: string;          // YYYY-MM-DD
  start: string;         // HH:MM
  end: string;           // HH:MM
  onClose: () => void;
  onBooked?: (booking: any) => void;
}

function rId(r: Resource) { return r.id || r.ID || ''; }
function rName(r: Resource) { return r.name || r.Name || ''; }

// Dedicated booking dialog — replaces the inline calendar prompt.
// Surfaces title, recurrence, services add-ons, the private flag and
// the meeting URL inside one form so the user only confirms once.
// Validates against the tenant rule set via useBookingRules so the SPA
// matches the server-side guard. When no room is pre-selected the dialog
// shows a resource picker so the user can drag any open slot and choose
// the room here (Teams-style), rather than filtering first.
export function BookingModal({ resource, resources, date, start, end, onClose, onBooked }: Props) {
  const toast = useToast();
  const { validate, allowsPattern } = useBookingRules();

  const choices = resources ?? (resource ? [resource] : []);
  const [selResId, setSelResId] = useState(resource ? rId(resource) : '');

  const [title, setTitle] = useState('');
  const [meetingUrl, setMeetingUrl] = useState('');
  const [isPrivate, setPrivate] = useState(false);
  const [recur, setRecur] = useState(false);
  const [pattern, setPattern] = useState<'daily' | 'weekly' | 'bi-weekly' | 'monthly'>('weekly');
  const [count, setCount] = useState(4);
  const [services, setServices] = useState<string[]>([]);
  const [busy, setBusy] = useState(false);
  const [result, setResult] = useState<any | null>(null);

  const ruleError = useMemo(() => validate({ date, start, end }), [date, start, end, validate]);

  const selected = useMemo(
    () => choices.find((r) => rId(r) === selResId),
    [choices, selResId]
  );

  const resName  = selected ? rName(selected) : '';
  const resLoc   = selected ? (selected.location || selected.Location || '') : '';
  const resCap   = selected ? (selected.capacity || selected.Capacity || 0) : 0;
  const resId    = selResId;
  const needsApproval = !!(selected && (selected.requiresApproval ?? selected.RequiresApproval));
  const showPicker = choices.length > 1 || !resource;

  // Pre-defined service add-ons — admins can override these via the
  // tenant studio later; for now this matches v1's hard-coded list.
  const SERVICE_OPTIONS = ['Catering', 'IT setup', 'AV equipment', 'Whiteboard'];

  function toggleService(opt: string) {
    setServices((arr) => (arr.includes(opt) ? arr.filter((x) => x !== opt) : [...arr, opt]));
  }

  function formatDate(d: string) {
    if (!d) return '';
    return new Date(`${d}T00:00:00`).toLocaleDateString(undefined, {
      weekday: 'long', month: 'short', day: 'numeric',
    });
  }

  async function submit() {
    if (ruleError) { toast.error('Cannot book', ruleError); return; }
    if (!resId) { toast.warning('Pick a resource'); return; }
    if (!title.trim()) { toast.warning('Title required'); return; }
    setBusy(true);
    try {
      const startIso = new Date(`${date}T${start}:00`).toISOString();
      const endIso = new Date(`${date}T${end}:00`).toISOString();
      let r: any;
      if (recur) {
        // Recurring bookings go to the dedicated /bookings/recurring
        // endpoint — the plain /bookings create() silently ignores the
        // recurrence block, so the series never materialised (QA #4).
        r = await api.createRecurringBooking({
          resourceId: resId,
          firstStart: startIso,
          firstEnd: endIso,
          pattern,
          count,
          title: title.trim(),
          meetingUrl: meetingUrl.trim() || undefined,
          isPrivate,
        });
      } else {
        r = await api.createBooking({
          resourceId: resId,
          startTime: startIso,
          endTime: endIso,
          title: title.trim(),
          meetingUrl: meetingUrl.trim() || undefined,
          isPrivate,
          services: services.length ? services : undefined,
        });
      }
      setResult(r || { status: 'Confirmed' });
      toast.success(recur ? 'Recurring booking submitted' : 'Booking submitted');
      setTimeout(() => { onBooked?.(r); onClose(); }, 900);
    } catch (e: any) {
      toast.error('Booking failed', e.displayMessage || e.message);
    } finally { setBusy(false); }
  }

  return (
    <Modal
      title="Confirm booking"
      onClose={onClose}
      footer={<>
        <span className="spacer" />
        <button className="btn ghost" onClick={onClose}>Cancel</button>
        <button className="btn primary" disabled={busy || !!result || !!ruleError || !resId} onClick={submit}>
          {busy && <Loader2 size={14} className="spin" />} Confirm booking
        </button>
      </>}
    >
      <div className="bm-summary">
        <div className="bm-thumb"><Building2 size={20} color="white" /></div>
        <div style={{ flex: 1 }}>
          {showPicker ? (
            <label style={{ margin: 0 }}>Resource*
              <select value={selResId} onChange={(e) => setSelResId(e.target.value)}>
                <option value="">Choose a resource…</option>
                {choices.map((r) => (
                  <option key={rId(r)} value={rId(r)}>
                    {rName(r)}{(r.location || r.Location) ? ` · ${r.location || r.Location}` : ''}
                  </option>
                ))}
              </select>
            </label>
          ) : (
            <h3 style={{ margin: 0 }}>{resName}</h3>
          )}
          {selected && (
            <small className="muted">{resLoc}{resCap ? ` · ${resCap} pax` : ''}</small>
          )}
        </div>
      </div>

      <div className="bm-timerow">
        <span><Calendar size={14} /> {formatDate(date)}</span>
        <span><Clock size={14} /> {start} – {end}</span>
        <span className={`tag ${needsApproval ? 'warning' : 'ok'}`}>
          {needsApproval ? 'Requires approval' : 'Auto-approved'}
        </span>
      </div>

      <label>Title*
        <input value={title} onChange={(e) => setTitle(e.target.value)}
               placeholder="e.g. Weekly team sync" />
      </label>

      <label>Meeting URL
        <input value={meetingUrl} onChange={(e) => setMeetingUrl(e.target.value)}
               placeholder="https://teams.microsoft.com/…" />
      </label>

      <div className="field">
        <label>Services / add-ons</label>
        <div className="chip-grid">
          {SERVICE_OPTIONS.map((opt) => (
            <label key={opt} className="dep-chip">
              <input type="checkbox" checked={services.includes(opt)} onChange={() => toggleService(opt)} />
              {opt}
            </label>
          ))}
        </div>
      </div>

      <div className="field bm-box">
        <div className="row gap" style={{ alignItems: 'center' }}>
          <Switch checked={recur} onChange={setRecur} label="Recurring" />
          <span><Repeat size={13} /> Make this recurring</span>
        </div>
        {recur && (
          <div className="grid-2 mt">
            <label>Pattern
              <select value={pattern} onChange={(e) => setPattern(e.target.value as any)}>
                {allowsPattern('daily')   && <option value="daily">Daily</option>}
                {allowsPattern('weekly')  && <option value="weekly">Weekly</option>}
                {allowsPattern('weekly')  && <option value="bi-weekly">Bi-weekly</option>}
                {allowsPattern('monthly') && <option value="monthly">Monthly</option>}
              </select>
            </label>
            <label>Occurrences
              <input type="number" min={1} max={100} value={count}
                     onChange={(e) => setCount(+e.target.value || 1)} />
            </label>
          </div>
        )}
      </div>

      <div className="row gap mt" style={{ alignItems: 'center' }}>
        <Switch checked={isPrivate} onChange={setPrivate} label="Private appointment" />
        <span><Lock size={13} /> Mark as private (hide subject from other viewers)</span>
      </div>

      {result && (
        <div className="bm-result mt">
          <Check size={16} />
          <div>
            <b>{result.requires_approval ? 'Pending approval' : 'Booking confirmed'}</b>
            <p className="muted small">
              {result.requires_approval
                ? 'A room admin will review this shortly.'
                : 'You\'ll get an email confirmation in a moment.'}
            </p>
          </div>
        </div>
      )}

      {ruleError && <div className="err mt">{ruleError}</div>}
    </Modal>
  );
}
