// fsd-v2/frontend/src/pages/AdminResourceTypes.tsx
import { useEffect, useState } from 'react';
import { api } from '../api/client';
import { Modal } from '../components/Modal';
import { useT } from '../hooks/useT';
import { confirmDialog, alertDialog } from '../stores/confirm';

// Admin-extensible asset type catalog. Built-ins (`isBuiltin`) show as
// locked rows. Mirrors v1 AdminResourceTypes.vue.
const blank = {
  key: '', label: '', icon: 'box', color: '#3b82f6',
  defaultCapacity: 0, defaultBookingMode: 'exclusive',
  defaultRequiresApproval: false, displayOrder: 0, isActive: true,
};

export function AdminResourceTypes() {
  const { t } = useT();
  const [items, setItems] = useState<any[]>([]);
  const [editing, setEditing] = useState<any | null>(null);
  useEffect(() => { load(); }, []);
  function load() { api.adminResourceTypes().then(setItems); }

  async function save() {
    try {
      if (editing.id) await api.updateResourceType(editing.id, editing);
      else            await api.createResourceType(editing);
      setEditing(null); load();
    } catch (e: any) { await alertDialog({ title: t('adminResourceTypes.saveFailed'), message: e.displayMessage, tone: 'danger' }); }
  }
  async function remove(r: any) {
    if (r.isBuiltin) { await alertDialog({ title: t('adminResourceTypes.builtinCannotDelete'), tone: 'danger' }); return; }
    if (!(await confirmDialog({ title: t('adminResourceTypes.deleteConfirm', { name: r.label }), tone: 'danger', confirmText: t('common.delete'), cancelText: t('common.cancel') }))) return;
    await api.deleteResourceType(r.id); load();
  }

  return (
    <div>
      <header className="page-head">
        <h1>{t('adminResourceTypes.title')}</h1>
        <button className="btn primary" onClick={() => setEditing({ ...blank })}>+ {t('adminResourceTypes.addType')}</button>
      </header>
      <table className="data">
        <thead><tr><th>{t('adminResourceTypes.key')}</th><th>{t('adminResourceTypes.label')}</th><th>{t('adminResourceTypes.icon')}</th><th>{t('adminResourceTypes.color')}</th><th>{t('adminResourceTypes.defaultCap')}</th><th>{t('adminResourceTypes.mode')}</th><th>{t('adminResourceTypes.approval')}</th><th></th></tr></thead>
        <tbody>
          {items.map((r) => (
            <tr key={r.id}>
              <td><code>{r.key}</code>{r.isBuiltin && <span className="tag" style={{ marginLeft: 6 }}>{t('adminResourceTypes.builtin')}</span>}</td>
              <td>{r.label}</td>
              <td>{r.icon}</td>
              <td><span style={{ display: 'inline-block', width: 16, height: 16, background: r.color, borderRadius: 3, verticalAlign: 'middle' }}/> {r.color}</td>
              <td>{r.defaultCapacity}</td>
              <td>{r.defaultBookingMode}</td>
              <td>{r.defaultRequiresApproval ? t('common.yes') : t('common.no')}</td>
              <td>
                <button className="btn ghost" onClick={() => setEditing({ ...r })}>{t('adminResourceTypes.edit')}</button>
                <button className="btn danger" onClick={() => remove(r)} disabled={r.isBuiltin}>{t('common.delete')}</button>
              </td>
            </tr>
          ))}
        </tbody>
      </table>

      {editing && (
        <Modal title={editing.id ? t('adminResourceTypes.editType', { name: editing.label }) : t('adminResourceTypes.addType')} onClose={() => setEditing(null)}
          footer={<><span className="spacer"/><button className="btn ghost" onClick={() => setEditing(null)}>{t('common.cancel')}</button><button className="btn primary" onClick={save}>{t('common.save')}</button></>}>
          <div className="grid-2">
            <label>{t('adminResourceTypes.key')}<input value={editing.key} onChange={(e) => setEditing({ ...editing, key: e.target.value })} disabled={editing.isBuiltin} /></label>
            <label>{t('adminResourceTypes.label')}<input value={editing.label} onChange={(e) => setEditing({ ...editing, label: e.target.value })} /></label>
            <label>{t('adminResourceTypes.iconLucide')}<input value={editing.icon} onChange={(e) => setEditing({ ...editing, icon: e.target.value })} /></label>
            <label>{t('adminResourceTypes.color')}
              <div className="row gap-sm">
                <input type="color" value={editing.color} onChange={(e) => setEditing({ ...editing, color: e.target.value })} />
                <input type="text" value={editing.color} maxLength={7} placeholder="#3b82f6"
                  onChange={(e) => setEditing({ ...editing, color: e.target.value })} style={{ flex: 1 }} />
              </div>
            </label>
            <label>{t('adminResourceTypes.defaultCapacity')}<input type="number" min={0} value={editing.defaultCapacity} onChange={(e) => setEditing({ ...editing, defaultCapacity: +e.target.value })} /></label>
            <label>{t('adminResourceTypes.displayOrder')}<input type="number" value={editing.displayOrder} onChange={(e) => setEditing({ ...editing, displayOrder: +e.target.value })} /></label>
            <label>{t('adminResourceTypes.bookingMode')}
              <select value={editing.defaultBookingMode} onChange={(e) => setEditing({ ...editing, defaultBookingMode: e.target.value })}>
                <option value="exclusive">{t('adminResourceTypes.modeExclusive')}</option>
                <option value="shared">{t('adminResourceTypes.modeShared')}</option>
              </select>
            </label>
          </div>
          <label className="row"><input type="checkbox" checked={!!editing.defaultRequiresApproval} onChange={(e) => setEditing({ ...editing, defaultRequiresApproval: e.target.checked })} /> {t('adminResourceTypes.requiresApprovalDefault')}</label>
          <label className="row"><input type="checkbox" checked={!!editing.isActive} onChange={(e) => setEditing({ ...editing, isActive: e.target.checked })} /> {t('common.active')}</label>
        </Modal>
      )}
    </div>
  );
}

// src/presentation/web/spa/src/views/AdminResourceTypes.vue
<template>
  <div>
    <div class="row" style="justify-content: space-between; align-items: flex-end;">
      <div>
        <h1 class="page-title">{{ $t('admin.resourceTypes.title') }}</h1>
        <p class="muted">{{ $t('admin.resourceTypes.subtitle') }}</p>
      </div>
      <button class="btn" @click="newType"><Plus :size="14"/> {{ $t('admin.resourceTypes.new') }}</button>
    </div>

    <div v-if="!items.length" class="empty mt-lg">
      <Boxes :size="32"/>
      <p>{{ $t('admin.resourceTypes.empty') }}</p>
    </div>

    <div v-else class="grid mt-lg" style="grid-template-columns: repeat(auto-fill, minmax(260px, 1fr)); gap: 14px;">
      <div v-for="t in items" :key="t.Key" class="card hover" @click="edit(t)">
        <div class="row" style="justify-content: space-between; align-items: flex-start;">
          <div>
            <div style="font-weight:600;">{{ t.Label }}</div>
            <small class="muted">{{ t.Key }}</small>
          </div>
          <div class="col" style="text-align:right;">
            <span class="tag" :class="t.IsBuiltin ? 'info' : 'brand'">
              {{ t.IsBuiltin ? $t('admin.resourceTypes.builtin') : $t('admin.resourceTypes.custom') }}
            </span>
            <span class="tag mt-xs" :class="t.DefaultBookingMode === 'shared' ? 'warning' : ''">
              {{ t.DefaultBookingMode === 'shared'
                  ? $t('admin.resources.modeShared')
                  : $t('admin.resources.modeExclusive') }}
            </span>
          </div>
        </div>
        <div class="row gap mt-sm muted text-sm">
          <span>{{ $t('admin.resourceTypes.defaultCap') }}: {{ t.DefaultCapacity }}</span>
          <span v-if="t.DefaultRequiresApproval">· {{ $t('admin.resources.requiresApproval') }}</span>
        </div>
      </div>
    </div>

    <Modal v-if="editing" @close="editing = null" :title="editing.Key ? $t('admin.resourceTypes.edit') : $t('admin.resourceTypes.new')">
      <div class="grid-2">
        <label class="field"><span>{{ $t('admin.resourceTypes.key') }}</span>
          <input v-model="editing.Key" :disabled="!!editing.ID" placeholder="e.g. gym"/></label>
        <label class="field"><span>{{ $t('admin.resourceTypes.label') }}</span>
          <input v-model="editing.Label" placeholder="Gym room"/></label>
        <label class="field"><span>{{ $t('admin.resourceTypes.icon') }}</span>
          <input v-model="editing.Icon" placeholder="dumbbell"/></label>
        <label class="field"><span>{{ $t('admin.resourceTypes.color') }}</span>
          <input type="color" v-model="editing.Color"/></label>
        <label class="field"><span>{{ $t('admin.resourceTypes.defaultCap') }}</span>
          <input type="number" min="1" v-model.number="editing.DefaultCapacity"/></label>
        <label class="field"><span>{{ $t('admin.resourceTypes.defaultMode') }}</span>
          <select v-model="editing.DefaultBookingMode">
            <option value="exclusive">{{ $t('admin.resources.modeExclusive') }}</option>
            <option value="shared">{{ $t('admin.resources.modeShared') }}</option>
          </select></label>
      </div>
      <div class="row gap mt">
        <label class="toggle"><input type="checkbox" v-model="editing.DefaultRequiresApproval"/>
          <span>{{ $t('admin.resources.requiresApproval') }}</span></label>
        <label class="toggle"><input type="checkbox" v-model="editing.IsActive"/>
          <span>{{ $t('admin.resources.active') }}</span></label>
      </div>
      <template #footer>
        <button v-if="editing.ID && !editing.IsBuiltin" class="btn ghost danger" @click="remove">
          <Trash2 :size="13"/> {{ $t('common.delete') }}
        </button>
        <span class="space"></span>
        <button class="btn ghost" @click="editing = null">{{ $t('common.cancel') }}</button>
        <button class="btn" @click="save"><Save :size="13"/> {{ $t('common.save') }}</button>
      </template>
    </Modal>
  </div>
</template>

<script setup>
import { onMounted, ref } from 'vue'
import { Plus, Boxes, Save, Trash2 } from 'lucide-vue-next'
import { useI18n } from 'vue-i18n'
import Modal from '../components/Modal.vue'
import { api } from '../api'
import { useToastStore } from '../stores/toast'

const items = ref([])
const editing = ref(null)
const { t } = useI18n()
const toasts = useToastStore()

async function load() {
  try { items.value = await api.listResourceTypes() || [] }
  catch (e) { toasts.error('Could not load', e.message) }
}
onMounted(load)

function newType() {
  editing.value = {
    Key: '', Label: '', Icon: '', Color: '#0a1f44',
    DefaultCapacity: 4, DefaultBookingMode: 'exclusive',
    DefaultRequiresApproval: false, IsActive: true, DisplayOrder: 100
  }
}
function edit(t) { editing.value = { ...t } }

async function save() {
  try {
    if (editing.value.ID) await api.updateResourceType(editing.value.Key, editing.value)
    else                  await api.createResourceType(editing.value)
    toasts.success(t('common.saved'))
    editing.value = null
    await load()
  } catch (e) { toasts.error('Save failed', e.message) }
}

async function remove() {
  if (!confirm(t('admin.resourceTypes.confirmDelete'))) return
  try {
    await api.deleteResourceType(editing.value.Key)
    editing.value = null
    await load()
  } catch (e) { toasts.error('Delete failed', e.message) }
}
</script>
