// fsd-v2/frontend/src/pages/AdminDepartments.tsx
import { useEffect, useMemo, useState } from 'react';
import { Plus, Building, ChevronRight, CornerDownRight, Save, Trash2 } from 'lucide-react';
import { api } from '../api/client';
import { useToast } from '../stores/toast';
import { Modal } from '../components/Modal';
import { Skeleton } from '../components/Skeleton';
import { EmptyState } from '../components/EmptyState';
import { useT } from '../hooks/useT';
import { confirmDialog } from '../stores/confirm';

interface Dept {
  id: string;
  name: string;
  code?: string;
  parentId?: string | null;
}

interface TreeRow extends Dept {
  _depth: number;
  _childCount: number;
}

function initials(s: string) {
  return (s || '').split(/\s+/).map((p) => p[0]).join('').slice(0, 2).toUpperCase();
}
function hueBackground(s: string) {
  let h = 0;
  for (let i = 0; i < s.length; i++) h = (h * 31 + s.charCodeAt(i)) >>> 0;
  return `linear-gradient(135deg, hsl(${h % 360} 60% 45%), hsl(${(h + 30) % 360} 70% 55%))`;
}

// Port of v1's AdminDepartments.vue — full CRUD on the M2M-backed
// department tree. The flattening visitor is identical to v1's so the
// indentation lines up the same way.
export function AdminDepartments() {
  const { t } = useT();
  const toast = useToast();
  const [loading, setLoading] = useState(true);
  const [items, setItems] = useState<Dept[]>([]);
  const [editing, setEditing] = useState<Partial<Dept> | null>(null);
  const [busy, setBusy] = useState(false);

  useEffect(() => { load(); }, []);
  async function load() {
    setLoading(true);
    try { setItems(await api.departments() || []); }
    catch (e: any) { toast.error(t('adminDepartments.loadFailed'), e.displayMessage || e.message); }
    finally { setLoading(false); }
  }

  const tree = useMemo<TreeRow[]>(() => {
    const byParent: Record<string, Dept[]> = {};
    for (const d of items) {
      const p = d.parentId || '';
      (byParent[p] = byParent[p] || []).push(d);
    }
    const out: TreeRow[] = [];
    const seen = new Set<string>();
    function walk(parentId: string, depth: number) {
      const kids = (byParent[parentId] || []).sort((a, b) => (a.name || '').localeCompare(b.name || ''));
      for (const d of kids) {
        if (seen.has(d.id)) continue;
        seen.add(d.id);
        out.push({ ...d, _depth: depth, _childCount: (byParent[d.id] || []).length });
        walk(d.id, depth + 1);
      }
    }
    walk('', 0);
    for (const d of items) if (!seen.has(d.id)) out.push({ ...d, _depth: 0, _childCount: 0 });
    return out;
  }, [items]);

  async function save() {
    if (!editing?.name?.trim()) { toast.warning(t('adminDepartments.nameRequired')); return; }
    setBusy(true);
    try {
      const payload = { name: editing.name, code: editing.code, parentId: editing.parentId || undefined };
      if (editing.id) await api.updateDepartment(editing.id, payload);
      else            await api.createDepartment(payload);
      toast.success(t('common.saved'));
      setEditing(null);
      load();
    } catch (e: any) { toast.error(t('adminDepartments.saveFailed'), e.displayMessage || e.message); }
    finally { setBusy(false); }
  }

  async function remove() {
    if (!editing?.id) return;
    if (!(await confirmDialog({ title: t('adminDepartments.deleteConfirm', { name: editing.name }), tone: 'danger', confirmText: t('common.delete'), cancelText: t('common.cancel') }))) return;
    setBusy(true);
    try {
      await api.deleteDepartment(editing.id);
      toast.success(t('adminDepartments.deleted'));
      setEditing(null);
      load();
    } catch (e: any) { toast.error(t('adminDepartments.deleteFailed'), e.displayMessage || e.message); }
    finally { setBusy(false); }
  }

  return (
    <div>
      <header className="page-head">
        <div>
          <h1>{t('adminDepartments.title')}</h1>
          <p className="muted small">{t('adminDepartments.subtitle')}</p>
        </div>
        <button className="btn primary" onClick={() => setEditing({ name: '', code: '', parentId: '' })}>
          <Plus size={14} /> {t('adminDepartments.newDepartment')}
        </button>
      </header>

      {loading ? (
        <div>{[1, 2, 3, 4].map((n) => (
          <div key={n} className="card" style={{ padding: 12, marginBottom: 6 }}><Skeleton height="32px" /></div>
        ))}</div>
      ) : !items.length ? (
        <EmptyState icon={Building} title={t('adminDepartments.emptyTitle')}
                    description={t('adminDepartments.emptyDescription')} />
      ) : (
        <div>
          {tree.map((row) => (
            <div key={row.id} className="dept-row card" style={{ marginLeft: row._depth * 28 }}
                 onClick={() => setEditing({ ...row })}>
              {row._depth > 0 && <CornerDownRight size={14} className="muted" />}
              <div className="dept-badge" style={{ background: hueBackground(row.name) }}>
                {initials(row.name)}
              </div>
              <div style={{ flex: 1 }}>
                <div style={{ fontWeight: 500 }}>{row.name}</div>
                <small className="muted">
                  {row.code || '—'}{row._childCount > 0 ? ` · ${t('adminDepartments.subUnitCount', { count: row._childCount })}` : ''}
                </small>
              </div>
              <ChevronRight size={16} className="muted" />
            </div>
          ))}
        </div>
      )}

      {editing && (
        <Modal
          title={editing.id ? t('adminDepartments.editDepartment', { name: editing.name }) : t('adminDepartments.createDepartment')}
          onClose={() => setEditing(null)}
          footer={<>
            {editing.id && <button className="btn danger" disabled={busy} onClick={remove}>
              <Trash2 size={13} /> {t('common.delete')}
            </button>}
            <span className="spacer" />
            <button className="btn ghost" onClick={() => setEditing(null)}>{t('common.cancel')}</button>
            <button className="btn primary" disabled={busy} onClick={save}>
              <Save size={13} /> {t('common.save')}
            </button>
          </>}
        >
          <label>{t('adminDepartments.name')}
            <input value={editing.name || ''} onChange={(e) => setEditing({ ...editing, name: e.target.value })} />
          </label>
          <label>{t('adminDepartments.code')}
            <input value={editing.code || ''} onChange={(e) => setEditing({ ...editing, code: e.target.value })}
                   placeholder="OPS / TRN / ADM" />
          </label>
          <label>{t('adminDepartments.parent')}
            <select value={editing.parentId || ''} onChange={(e) => setEditing({ ...editing, parentId: e.target.value || null })}>
              <option value="">{t('adminDepartments.topLevel')}</option>
              {items.filter((d) => d.id !== editing.id).map((d) =>
                <option key={d.id} value={d.id}>{d.name}</option>)}
            </select>
          </label>
        </Modal>
      )}
    </div>
  );
}

// src/presentation/web/spa/src/views/AdminDepartments.vue
<template>
  <div class="page-header mb-lg">
    <div>
      <h1>{{ $t('admin.departments.title') }}</h1>
      <p class="muted text-md mt-sm">{{ $t('admin.departments.subtitle') }}</p>
    </div>
    <button class="btn" @click="openNew"><Plus :size="14"/> {{ $t('admin.departments.new') }}</button>
  </div>

  <div v-if="loading">
    <div class="card mb" v-for="n in 4" :key="n"><Skeleton height="40px"/></div>
  </div>
  <EmptyState v-else-if="!items.length" :icon="Building" :title="$t('admin.departments.empty')"/>
  <div v-else>
    <div v-for="row in tree" :key="row.ID"
         class="card hover dept-row" :style="{ marginLeft: row._depth * 28 + 'px' }" @click="open(row)">
      <CornerDownRight v-if="row._depth" :size="14" class="muted" style="margin-right:-6px;"/>
      <div class="badge" :style="{ background: hue(row.Name) }">{{ initials(row.Name) }}</div>
      <div class="space">
        <div style="font-weight: 500;">{{ row.Name }}</div>
        <small class="muted">{{ row.Code || '—' }}<span v-if="row._childCount"> · {{ row._childCount }} sub-unit(s)</span></small>
      </div>
      <ChevronRight :size="16" class="muted"/>
    </div>
  </div>

  <Modal v-if="editing" @close="editing = null" :title="editing.ID ? $t('admin.departments.edit') : $t('admin.departments.create')">
    <label class="field"><span>{{ $t('admin.departments.name') }}</span><input v-model="editing.Name"/></label>
    <label class="field mt"><span>{{ $t('admin.departments.code') }}</span><input v-model="editing.Code" placeholder="OPS / TRN / ADM"/></label>
    <label class="field mt">
      <span>{{ $t('admin.departments.parent') }}</span>
      <select v-model="editing.ParentID">
        <option value="">—</option>
        <option v-for="d in items.filter(x => x.ID !== editing.ID)" :key="d.ID" :value="d.ID">{{ d.Name }}</option>
      </select>
    </label>
    <template #footer>
      <button class="btn ghost danger" v-if="editing.ID" @click="del" :disabled="busy"><Trash2 :size="13"/> {{ $t('common.delete') }}</button>
      <span class="space"></span>
      <button class="btn ghost" @click="editing = null">{{ $t('common.cancel') }}</button>
      <button class="btn" @click="save" :disabled="busy"><Save :size="13"/> {{ $t('common.save') }}</button>
    </template>
  </Modal>
</template>

<script setup>
import { computed, onMounted, ref } from 'vue'
import { Plus, Building, ChevronRight, CornerDownRight, Save, Trash2 } from 'lucide-vue-next'
import { useI18n } from 'vue-i18n'
import Skeleton from '../components/Skeleton.vue'
import EmptyState from '../components/EmptyState.vue'
import Modal from '../components/Modal.vue'
import { api } from '../api'
import { useToastStore } from '../stores/toast'

const { t } = useI18n()
const toasts = useToastStore()
const loading = ref(true)
const items = ref([])
const editing = ref(null)
const busy = ref(false)

// Flatten the parent/child graph into a depth-tagged, pre-ordered list so
// the template can render an indented hierarchy without recursion.
const tree = computed(() => {
  const byParent = {}
  for (const d of items.value) {
    const p = d.ParentID || ''
    ;(byParent[p] = byParent[p] || []).push(d)
  }
  const out = []
  const seen = new Set()
  const walk = (parentId, depth) => {
    for (const d of (byParent[parentId] || []).sort((a, b) => (a.Name || '').localeCompare(b.Name || ''))) {
      if (seen.has(d.ID)) continue
      seen.add(d.ID)
      out.push({ ...d, _depth: depth, _childCount: (byParent[d.ID] || []).length })
      walk(d.ID, depth + 1)
    }
  }
  walk('', 0)
  // Orphans (parent id points to a missing/filtered dept) still surface.
  for (const d of items.value) if (!seen.has(d.ID)) out.push({ ...d, _depth: 0, _childCount: 0 })
  return out
})

onMounted(load)
async function load() {
  loading.value = true
  try { items.value = await api.listDepartments() || [] }
  catch (e) { toasts.error('Failed', e.message) }
  finally { loading.value = false }
}
function open(d) { editing.value = JSON.parse(JSON.stringify(d)) }
function openNew() { editing.value = { Name: '', Code: '', ParentID: '' } }
async function save() {
  busy.value = true
  try {
    if (editing.value.ID) await api.updateDepartment(editing.value.ID, editing.value)
    else                  await api.createDepartment(editing.value)
    toasts.success(t('common.saved'))
    editing.value = null; load()
  } catch (e) { toasts.error('Save failed', e.message) }
  finally { busy.value = false }
}
async function del() {
  if (!confirm(t('admin.departments.confirmDelete'))) return
  busy.value = true
  try {
    await api.deleteDepartment(editing.value.ID)
    toasts.success(t('common.done'))
    editing.value = null; load()
  } catch (e) { toasts.error('Delete failed', e.message) }
  finally { busy.value = false }
}

function initials(s) { return (s || '').split(/\s+/).map(p => p[0]).join('').slice(0,2).toUpperCase() }
function hue(s) {
  let h = 0; for (const c of s) h = (h*31 + c.charCodeAt(0)) >>> 0
  return `linear-gradient(135deg, hsl(${h%360} 60% 45%), hsl(${(h+30)%360} 70% 55%))`
}
</script>

<style scoped>
.page-header { display: flex; justify-content: space-between; align-items: flex-start; gap: 12px; flex-wrap: wrap; }
.dept-row { display: grid; grid-template-columns: 36px 1fr auto; gap: 14px; align-items: center; margin-bottom: 8px; cursor: pointer; }
.badge { width: 36px; height: 36px; border-radius: 10px; color: white; font-weight: 600; font-size: 12px; display: grid; place-items: center; }
</style>
