// src/presentation/web/spa/src/views/AdminUsers.vue
<template>
  <div class="page-header mb-lg">
    <div>
      <h1>{{ $t('admin.users.title') }}</h1>
      <p class="muted text-md mt-sm">{{ $t('admin.users.subtitle') }}</p>
    </div>
    <button class="btn" @click="openNew"><Plus :size="14"/> {{ $t('admin.users.new') }}</button>
  </div>

  <div class="card mb">
    <div class="search" style="max-width:360px;">
      <Search class="icon" :size="14"/>
      <input v-model="q" :placeholder="$t('admin.users.searchPh')" />
    </div>
  </div>

  <div v-if="loading">
    <div class="card mb" v-for="n in 5" :key="n"><Skeleton height="48px"/></div>
  </div>
  <EmptyState v-else-if="!filtered.length" :icon="Users" :title="$t('admin.users.empty')"/>

  <div v-else class="card" style="padding:0; overflow:hidden;">
    <div class="user-row header">
      <div>{{ $t('admin.users.user') }}</div>
      <div>{{ $t('admin.users.role') }}</div>
      <div>{{ $t('admin.users.regions') }}</div>
      <div>{{ $t('admin.users.status') }}</div>
      <div></div>
    </div>
    <div class="user-row" v-for="u in filtered" :key="u.ID">
      <div class="row gap" style="min-width:0;">
        <Avatar :name="u.Username"/>
        <div style="min-width:0;">
          <div class="truncate" style="font-weight: 500;">{{ u.Username }}</div>
          <small class="muted truncate" style="display:block;">{{ u.DN || '—' }}</small>
        </div>
      </div>
      <div><span class="tag brand">{{ u.Role }}</span></div>
      <div class="muted text-sm">
        <span v-for="r in u.RegionAccess || []" :key="r" class="tag">{{ r }}</span>
        <span v-if="!(u.RegionAccess || []).length">—</span>
      </div>
      <div>
        <span class="tag" :class="u.IsActive ? 'success' : 'danger'">{{ u.IsActive ? $t('common.active') : $t('common.inactive') }}</span>
      </div>
      <div><button class="btn subtle sm" @click="open(u)"><Pencil :size="13"/></button></div>
    </div>
  </div>

  <Modal v-if="editing" @close="editing = null" :title="editing.ID ? $t('admin.users.edit') : $t('admin.users.create')">
    <div class="grid-2">
      <label class="field"><span>{{ $t('admin.users.username') }}</span><input v-model="editing.Username"/></label>
      <label class="field"><span>{{ $t('admin.users.dn') }}</span><input v-model="editing.DN" placeholder="CN=..."/></label>
      <label class="field">
        <span>{{ $t('admin.users.role') }}</span>
        <select v-model="editing.Role">
          <option>System Admin</option><option>Security Admin</option><option>Room Admin</option>
          <option>General User</option><option>Secretary</option>
        </select>
      </label>
      <label class="field"><span>{{ $t('admin.users.grade') }}</span><input v-model="editing.Grade" placeholder="SDO / DGFS / …"/></label>
    </div>
    <label class="field mt">
      <span>{{ $t('admin.users.regions') }}</span>
      <input :value="(editing.RegionAccess || []).join(', ')"
             @input="editing.RegionAccess = $event.target.value.split(',').map(s => s.trim()).filter(Boolean)"
             placeholder="Hong Kong, Kowloon, New Territories"/>
    </label>
    <label class="toggle mt">
      <input type="checkbox" v-model="editing.IsActive"/>
      <span>{{ $t('admin.users.activeAccount') }}</span>
    </label>
    <template #footer>
      <button class="btn ghost danger" v-if="editing.ID" @click="deactivate" :disabled="busy">
        <Trash2 :size="13"/> {{ $t('admin.users.deactivate') }}
      </button>
      <span class="space"></span>
      <button class="btn ghost" @click="editing = null">{{ $t('common.cancel') }}</button>
      <button class="btn" @click="save" :disabled="busy"><Save :size="13"/> {{ $t('common.save') }}</button>
    </template>
  </Modal>
</template>

<script setup>
import { computed, onMounted, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { Plus, Search, Users, Pencil, Save, Trash2 } from 'lucide-vue-next'
import Skeleton from '../components/Skeleton.vue'
import EmptyState from '../components/EmptyState.vue'
import Avatar from '../components/Avatar.vue'
import Modal from '../components/Modal.vue'
import { api } from '../api'
import { useToastStore } from '../stores/toast'

const { t } = useI18n()
const toasts = useToastStore()
const loading = ref(true)
const items = ref([])
const editing = ref(null)
const q = ref('')
const busy = ref(false)

const filtered = computed(() => items.value.filter(u =>
  !q.value || u.Username?.toLowerCase().includes(q.value.toLowerCase()) || u.DN?.toLowerCase().includes(q.value.toLowerCase())
))

onMounted(load)

async function load() {
  loading.value = true
  try { items.value = await api.listUsers() || [] }
  catch (e) { toasts.error('Could not load users', e.message) }
  finally { loading.value = false }
}

function open(u) { editing.value = JSON.parse(JSON.stringify(u)) }
function openNew() { editing.value = { Username: '', DN: '', Role: 'General User', Grade: '', RegionAccess: [], IsActive: true } }

async function save() {
  busy.value = true
  try {
    if (editing.value.ID) await api.updateUser(editing.value.ID, editing.value)
    else                  await api.createUser(editing.value)
    toasts.success(t('common.saved'))
    editing.value = null
    load()
  } catch (e) { toasts.error('Save failed', e.message) }
  finally { busy.value = false }
}

async function deactivate() {
  if (!confirm(t('admin.users.confirmDeactivate'))) return
  busy.value = true
  try {
    await api.deactivateUser(editing.value.ID)
    toasts.success(t('common.done'))
    editing.value = null
    load()
  } catch (e) { toasts.error('Failed', e.message) }
  finally { busy.value = false }
}
</script>

<style scoped>
.page-header { display: flex; justify-content: space-between; align-items: flex-start; gap: 12px; flex-wrap: wrap; }
.search { position: relative; }
.search .icon { position: absolute; left: 11px; top: 50%; transform: translateY(-50%); color: var(--text-muted); pointer-events: none; }
.search input { padding-left: 36px; }

.user-row {
  display: grid; grid-template-columns: 1.6fr 1fr 1.5fr 0.8fr 60px;
  gap: 14px; padding: 14px 18px; align-items: center;
  border-bottom: 1px solid var(--divider);
}
.user-row.header {
  background: var(--surface-inset); font-size: 11px; font-weight: 600;
  color: var(--text-muted); text-transform: uppercase; letter-spacing: 0.06em;
}
.user-row:last-child { border-bottom: 0; }
@media (max-width: 700px) {
  .user-row { grid-template-columns: 1fr; }
  .user-row.header { display: none; }
}
</style>

// fsd-v2/frontend/src/pages/AdminUsers.tsx
import { useEffect, useState } from 'react';
import { api } from '../api/client';
import { Modal } from '../components/Modal';
import { useT } from '../hooks/useT';
import { confirmDialog, alertDialog } from '../stores/confirm';
import { confirmDialog, alertDialog } from '../stores/confirm';

// Mirrors v1's AdminUsers.vue including the multi-select Departments
// section — the v2 backend persists membership through the same M2M
// join table, with the same tenant-scoped intersection guard.
export function AdminUsers() {
  const { t } = useT();
  const [users, setUsers] = useState<any[]>([]);
  const [depts, setDepts] = useState<any[]>([]);
  const [editing, setEditing] = useState<any | null>(null);
  const [busy, setBusy] = useState(false);

  useEffect(() => { load(); api.departments().then(setDepts).catch(() => {}); }, []);
  function load() { api.users().then(setUsers); }

  function openNew() {
    setEditing({ username: '', role: 'General User', password: '', regionAccess: [], departmentIds: [], isActive: true, mustChangePassword: true });
  }
  function open(u: any) {
    setEditing({ ...u, password: '', departmentIds: (u.departments || []).map((d: any) => d.id) });
  }
  function toggleDept(id: string) {
    setEditing((e: any) => {
      const s = new Set<string>(e.departmentIds || []);
      s.has(id) ? s.delete(id) : s.add(id);
      return { ...e, departmentIds: [...s] };
    });
  }
  async function save() {
    setBusy(true);
    try {
      if (editing.id) await api.updateUser(editing.id, editing);
      else            await api.createUser(editing);
      setEditing(null); load();
    } catch (e: any) { await alertDialog({ title: t('adminUsers.saveFailed'), message: e.displayMessage, tone: 'danger' }); }
    finally { setBusy(false); }
  }
  async function deactivate() {
    if (!(await confirmDialog({ title: t('adminUsers.deactivateConfirm'), tone: 'danger', confirmText: t('common.confirm'), cancelText: t('common.cancel') }))) return;
    setBusy(true);
    try { await api.deactivateUser(editing.id); setEditing(null); load(); }
    finally { setBusy(false); }
  }

  return (
    <div>
      <header className="page-head">
        <h1>{t('adminUsers.title')}</h1>
        <button className="btn primary" onClick={openNew}>+ {t('adminUsers.newUser')}</button>
      </header>

      <table className="data">
        <thead><tr><th>{t('adminUsers.username')}</th><th>{t('adminUsers.role')}</th><th>{t('adminUsers.regions')}</th><th>{t('adminUsers.departments')}</th><th>{t('common.status')}</th><th></th></tr></thead>
        <tbody>
          {users.map((u) => (
            <tr key={u.id}>
              <td>{u.username}</td>
              <td><span className="tag">{u.role}</span></td>
              <td className="muted">{(u.regionAccess || []).join(', ') || '—'}</td>
              <td className="muted">{(u.departments || []).map((d: any) => d.name).join(', ') || '—'}</td>
              <td><span className={`tag ${u.isActive ? 'ok' : 'bad'}`}>{u.isActive ? t('common.active') : t('common.inactive')}</span></td>
              <td><button className="btn ghost" onClick={() => open(u)}>{t('adminUsers.edit')}</button></td>
            </tr>
          ))}
        </tbody>
      </table>

      {editing && (
        <Modal
          title={editing.id ? t('adminUsers.editUser', { name: editing.username }) : t('adminUsers.createUser')}
          onClose={() => setEditing(null)}
          footer={<>
            {editing.id && <button className="btn danger" disabled={busy} onClick={deactivate}>{t('adminUsers.deactivate')}</button>}
            <span className="spacer" />
            <button className="btn ghost" onClick={() => setEditing(null)}>{t('common.cancel')}</button>
            <button className="btn primary" disabled={busy} onClick={save}>{t('common.save')}</button>
          </>}
        >
          <div className="grid-2">
            <label>{t('adminUsers.username')}<input value={editing.username || ''} onChange={(e) => setEditing({ ...editing, username: e.target.value })} /></label>
            <label>{t('adminUsers.role')}
              <select value={editing.role || ''} onChange={(e) => setEditing({ ...editing, role: e.target.value })}>
                <option>System Admin</option><option>Security Admin</option><option>Room Admin</option>
                <option>Secretary</option><option>General User</option>
              </select>
            </label>
            <label>{editing.id ? t('adminUsers.password') : t('adminUsers.initialPassword')} {editing.id && <span className="muted">{t('adminUsers.passwordKeepHint')}</span>}
              <input type="password" value={editing.password || ''} autoComplete="new-password"
                onChange={(e) => setEditing({ ...editing, password: e.target.value })} />
            </label>
            <label>{t('adminUsers.grade')}<input value={editing.grade || ''} onChange={(e) => setEditing({ ...editing, grade: e.target.value })} placeholder="SDO / DGFS / …" /></label>
          </div>

          <label className="row" style={{ alignItems: 'center', gap: 8 }}>
            <input type="checkbox" checked={!!editing.mustChangePassword}
              onChange={(e) => setEditing({ ...editing, mustChangePassword: e.target.checked })} />
            <span>{t('adminUsers.forceReset')}</span>
          </label>
          <label>{t('adminUsers.regionAccess')}
            <input value={(editing.regionAccess || []).join(', ')}
              onChange={(e) => setEditing({ ...editing, regionAccess: e.target.value.split(',').map(s => s.trim()).filter(Boolean) })} />
          </label>

          <div className="field">
            <label>{t('adminUsers.departments')}</label>
            {!depts.length && <p className="muted">{t('adminUsers.noDepartments')}</p>}
            <div className="dep-grid">
              {depts.map((d) => (
                <label key={d.id} className="dep-chip">
                  <input type="checkbox" checked={(editing.departmentIds || []).includes(d.id)} onChange={() => toggleDept(d.id)} />
                  {d.name}{d.code && <span className="muted"> · {d.code}</span>}
                </label>
              ))}
            </div>
          </div>

          <label className="row">
            <input type="checkbox" checked={!!editing.isActive} onChange={(e) => setEditing({ ...editing, isActive: e.target.checked })} />
            <span>{t('adminUsers.activeAccount')}</span>
          </label>
        </Modal>
      )}
    </div>
  );
}
