// src/presentation/web/spa/src/views/Approvals.vue
<template>
  <div class="page-header mb-lg">
    <div>
      <h1>{{ $t('approvals.title') }}</h1>
      <p class="muted text-md mt-sm">{{ $t('approvals.subtitle') }}</p>
    </div>
    <button class="btn ghost" @click="load"><RefreshCcw :size="14"/> {{ $t('common.refresh') }}</button>
  </div>

  <div class="stat-strip mb" v-if="!loading && items.length">
    <div class="stat"><small>Pending</small><b>{{ stats.pending }}</b></div>
    <div class="stat"><small>Multi-step chains</small><b>{{ stats.chained }}</b></div>
    <div class="stat"><small>Today</small><b>{{ stats.today }}</b></div>
    <div class="stat"><small>This week</small><b>{{ stats.week }}</b></div>
  </div>

  <div v-if="loading">
    <div class="card mb" v-for="n in 3" :key="n"><Skeleton height="84px"/></div>
  </div>
  <EmptyState v-else-if="!items.length" :icon="ShieldCheck"
              :title="$t('approvals.empty')"
              :description="$t('approvals.emptyDesc')"/>
  <div v-else>
    <article v-for="b in sortedItems" :key="b.ID" class="card approval-card mb"
             :class="{ overdue: isOverdue(b) }">
      <div class="thumb">
        <Clock :size="18" color="white"/>
      </div>
      <div class="space" style="min-width:0;">
        <div class="row gap-sm" style="align-items: baseline;">
          <h3 class="truncate">{{ resourceName(b.ResourceID) }}</h3>
          <span class="tag warning">{{ b.Status }}</span>
          <span v-if="(chains[b.ID] || []).length > 0" class="tag info">
            <GitBranch :size="11"/>
            {{ $t('approvals.chainStep', { current: currentStep(b.ID), total: (chains[b.ID] || []).length }) }}
          </span>
        </div>
        <div class="muted text-sm mt-sm row gap-sm" style="flex-wrap: wrap;">
          <span><CalendarDays :size="11"/> {{ formatDate(b.StartTime) }}</span>
          <span><Clock :size="11"/> {{ formatTime(b.StartTime) }} – {{ formatTime(b.EndTime) }}</span>
          <span><User :size="11"/> {{ requester(b) }}</span>
        </div>

        <!-- Chain progress timeline -->
        <div v-if="(chains[b.ID] || []).length > 0" class="mt">
          <ApprovalTimeline :steps="chains[b.ID]" :submitted-at="b.CreatedAt" />
        </div>

        <div v-if="b.MeetingURL" class="muted text-sm mt-sm">
          <Link :size="11"/> {{ b.MeetingURL }}
        </div>
      </div>
      <div class="row gap-sm" style="flex-shrink: 0;">
        <button class="btn ghost" :disabled="busyId === b.ID" @click="onDelegate(b)" title="Delegate to another approver">
          <UserCog :size="13"/> Delegate
        </button>
        <button class="btn ghost danger" :disabled="busyId === b.ID" @click="onReject(b)">
          <X :size="13"/> {{ $t('approvals.reject') }}
        </button>
        <button class="btn success" :disabled="busyId === b.ID" @click="onApprove(b)">
          <Check :size="13"/> {{ $t('approvals.approve') }}
        </button>
      </div>
    </article>
  </div>

  <Modal v-if="delegating" @close="delegating = null" title="Delegate approval">
    <p class="muted text-sm mb">
      Reassign the current pending step to another approver. This is recorded
      on the approval timeline (it is not a silent reassignment).
    </p>
    <label class="field">
      <span>Delegate to</span>
      <select v-model="delegateTo">
        <option value="" disabled>Select an approver…</option>
        <option v-for="u in users" :key="u.ID" :value="u.ID">
          {{ u.Username || u.ID }}<span v-if="u.Role"> — {{ u.Role }}</span>
        </option>
      </select>
    </label>
    <label class="field mt">
      <span>Reason (optional)</span>
      <textarea rows="2" v-model="delegateReason" placeholder="e.g. On leave — please cover"></textarea>
    </label>
    <template #footer>
      <button class="btn ghost" @click="delegating = null">{{ $t('common.cancel') }}</button>
      <button class="btn" :disabled="!delegateTo || busy" @click="confirmDelegate">
        <UserCog :size="13"/> Delegate
      </button>
    </template>
  </Modal>

  <Modal v-if="rejecting" @close="rejecting = null" :title="$t('approvals.rejectTitle')">
    <p class="muted text-sm mb">{{ $t('approvals.rejectHelp') }}</p>
    <label class="field">
      <span>{{ $t('approvals.reason') }}</span>
      <textarea rows="3" v-model="rejectReason" :placeholder="$t('approvals.reasonPh')"></textarea>
    </label>
    <template #footer>
      <button class="btn ghost" @click="rejecting = null">{{ $t('common.cancel') }}</button>
      <button class="btn danger" :disabled="!rejectReason || busy" @click="confirmReject">
        <X :size="13"/> {{ $t('approvals.reject') }}
      </button>
    </template>
  </Modal>
</template>

<script setup>
import { computed, onMounted, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import {
  RefreshCcw, ShieldCheck, Clock, CalendarDays, User, Check, X, Link, GitBranch, UserCog
} from 'lucide-vue-next'
import Skeleton from '../components/Skeleton.vue'
import EmptyState from '../components/EmptyState.vue'
import Modal from '../components/Modal.vue'
import ApprovalTimeline from '../components/ApprovalTimeline.vue'
import { api } from '../api'
import { useToastStore } from '../stores/toast'

const { t, locale } = useI18n()
const toasts = useToastStore()
const items = ref([])
const resources = ref([])
const users = ref([])
// chains[bookingID] = [{ ID, LevelName, Status, ApproverRole, … }]
const chains = ref({})
const loading = ref(true)
const busy = ref(false)
const busyId = ref(null)
const rejecting = ref(null)
const rejectReason = ref('')
const delegating = ref(null)
const delegateTo = ref('')
const delegateReason = ref('')

// Earliest pending-step due time for a booking (ms epoch), or Infinity.
function dueFor(b) {
  const steps = chains.value[b.ID] || []
  for (const s of steps) {
    if ((s.Status || '').toLowerCase() === 'pending' && (s.DueAt || s.due_at)) {
      return new Date(s.DueAt || s.due_at).getTime()
    }
  }
  return Infinity
}
function isOverdue(b) {
  const d = dueFor(b)
  return d !== Infinity && d < Date.now()
}
// SLA-priority order: closest-to-breach (and overdue) first.
const sortedItems = computed(() =>
  [...items.value].sort((a, b) => dueFor(a) - dueFor(b)))

const resourceMap = computed(() => Object.fromEntries(resources.value.map(r => [r.ID, r])))
const userMap = computed(() => Object.fromEntries(users.value.map(u => [u.ID, u])))

const stats = computed(() => {
  const now = new Date()
  const todayStr = now.toDateString()
  const weekAgo = new Date(now.getTime() - 7 * 86400000)
  let chained = 0, today = 0, week = 0
  for (const b of items.value) {
    if ((chains.value[b.ID] || []).length > 0) chained++
    const start = new Date(b.StartTime)
    if (start.toDateString() === todayStr) today++
    if (start >= weekAgo) week++
  }
  return { pending: items.value.length, chained, today, week }
})

onMounted(load)

async function load() {
  loading.value = true
  try {
    const [list, res, usrs] = await Promise.all([
      api.listApprovals(),
      api.listResources().catch(() => []),
      api.listUsers().catch(() => [])
    ])
    items.value = list || []
    resources.value = res || []
    users.value = usrs || []
    // Best-effort fetch chain steps for each booking — failures are silent
    // because most bookings won't have a chain.
    await Promise.all((items.value || []).map(async b => {
      try { chains.value[b.ID] = await api.approvalChain(b.ID) || [] }
      catch { chains.value[b.ID] = [] }
    }))
  } catch (e) { toasts.error('Could not load', e.message) }
  finally { loading.value = false }
}

function resourceName(id) { return resourceMap.value[id]?.Name || id }
function requester(b) {
  const u = userMap.value[b.UserID]
  return u?.Username || b.UserID || '—'
}
function formatDate(d) { return new Date(d).toLocaleDateString(locale.value, { weekday: 'short', month: 'short', day: 'numeric' }) }
function formatTime(d) { return new Date(d).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) }

// currentStep returns the 1-based index of the first pending step, or the
// total length if every step is decided.
function currentStep(bookingID) {
  const steps = chains.value[bookingID] || []
  for (let i = 0; i < steps.length; i++) {
    if (steps[i].Status === 'pending') return i + 1
  }
  return steps.length
}

async function onApprove(b) {
  busyId.value = b.ID
  try {
    await api.approveBooking(b.ID, '')
    toasts.success(t('approvals.approved'))
    // If chain → reload to show progress; if single-level → drop the row.
    if ((chains.value[b.ID] || []).length > 0) await load()
    else items.value = items.value.filter(x => x.ID !== b.ID)
  } catch (e) { toasts.error('Approval failed', e.message) }
  finally { busyId.value = null }
}

function onDelegate(b) { delegating.value = b; delegateTo.value = ''; delegateReason.value = '' }

async function confirmDelegate() {
  busy.value = true
  busyId.value = delegating.value.ID
  try {
    await api.delegateBooking(delegating.value.ID, delegateTo.value, delegateReason.value)
    toasts.success('Delegated', 'The pending step was reassigned.')
    delegating.value = null
    await load()
  } catch (e) { toasts.error('Delegate failed', e.message) }
  finally { busy.value = false; busyId.value = null }
}

function onReject(b) { rejecting.value = b; rejectReason.value = '' }

async function confirmReject() {
  busy.value = true
  busyId.value = rejecting.value.ID
  try {
    await api.rejectBooking(rejecting.value.ID, rejectReason.value)
    toasts.success(t('approvals.rejected'))
    items.value = items.value.filter(x => x.ID !== rejecting.value.ID)
    rejecting.value = null
  } catch (e) { toasts.error('Reject failed', e.message) }
  finally { busy.value = false; busyId.value = null }
}
</script>

<style scoped>
.page-header { display: flex; justify-content: space-between; align-items: flex-start; gap: 12px; flex-wrap: wrap; }
.approval-card {
  display: grid; grid-template-columns: 44px 1fr auto;
  gap: 14px; align-items: center;
}
.approval-card.overdue {
  border-color: color-mix(in srgb, var(--danger) 45%, transparent);
  box-shadow: inset 3px 0 0 var(--danger);
}
.thumb {
  width: 44px; height: 44px; border-radius: 12px;
  display: grid; place-items: center;
  background: linear-gradient(135deg, var(--warning), color-mix(in srgb, var(--warning) 60%, var(--brand-secondary)));
}
@media (max-width: 700px) {
  .approval-card { grid-template-columns: 1fr; }
}

.chain-strip {
  display: flex; align-items: center; gap: 0;
  padding: 8px 0;
}
.chain-step {
  display: inline-flex; align-items: center; gap: 6px;
  font-size: 11px; color: var(--text-muted);
  padding-right: 14px; position: relative;
}
.chain-step:not(:last-child)::after {
  content: ''; position: absolute; right: 4px; top: 50%;
  width: 6px; height: 1px; background: var(--border);
}
.chain-step .dot {
  width: 18px; height: 18px; border-radius: 50%;
  background: var(--surface-inset); border: 1px solid var(--border);
  display: grid; place-items: center;
  font-size: 10px; font-weight: 600; color: var(--text-muted);
}
.chain-step.approved .dot { background: var(--success); color: white; border-color: var(--success); }
.chain-step.rejected .dot { background: var(--danger);  color: white; border-color: var(--danger); }
.chain-step.pending  .dot { background: var(--brand-primary); color: white; border-color: var(--brand-primary); }
.chain-step.pending  .label { color: var(--text); font-weight: 500; }

.stat-strip {
  display: grid; grid-template-columns: repeat(auto-fit, minmax(140px, 1fr));
  gap: 10px;
}
.stat {
  background: var(--bg-elevated); border: 1px solid var(--border);
  border-radius: var(--radius); padding: 12px 14px;
  display: flex; flex-direction: column; gap: 2px;
}
.stat small {
  font-size: 10px; font-weight: 600; color: var(--text-muted);
  text-transform: uppercase; letter-spacing: 0.06em;
}
.stat b { font-size: 22px; font-weight: 700; color: var(--text); }
</style>

// fsd-v2/frontend/src/pages/Approvals.tsx
import { useEffect, useMemo, useState } from 'react';
import { RefreshCcw, Check, X, Clock, CalendarDays, User, UserCog, GitBranch } from 'lucide-react';
import { api } from '../api/client';
import { Modal } from '../components/Modal';
import { ApprovalTimeline } from '../components/ApprovalTimeline';
import { useT } from '../hooks/useT';
import { useToast } from '../stores/toast';

export function Approvals() {
  const { t } = useT();
  const toast = useToast();
  const [rows, setRows] = useState<any[]>([]);
  const [resources, setResources] = useState<any[]>([]);
  const [users, setUsers] = useState<any[]>([]);
  const [chains, setChains] = useState<Record<string, any[]>>({});
  const [loading, setLoading] = useState(true);
  const [busyId, setBusyId] = useState<string | null>(null);

  const [rejecting, setRejecting] = useState<any | null>(null);
  const [rejectReason, setRejectReason] = useState('');
  const [delegating, setDelegating] = useState<any | null>(null);
  const [delegateTo, setDelegateTo] = useState('');
  const [delegateReason, setDelegateReason] = useState('');

  useEffect(() => { load(); }, []);

  async function load() {
    setLoading(true);
    try {
      const [list, res, usrs] = await Promise.all([
        api.listApprovals(),
        api.resources().catch(() => []),
        api.users().catch(() => []),
      ]);
      setRows(list || []);
      setResources(res || []);
      setUsers(usrs || []);
      // Best-effort fetch chain per row — failures are silent because
      // single-level bookings have no chain.
      const next: Record<string, any[]> = {};
      await Promise.all((list || []).map(async (b: any) => {
        try { next[b.id] = await api.approvalChain(b.id) ?? []; }
        catch { next[b.id] = []; }
      }));
      setChains(next);
    } finally { setLoading(false); }
  }

  const resourceMap = useMemo(() => Object.fromEntries(resources.map((r) => [r.id, r])), [resources]);
  const userMap = useMemo(() => Object.fromEntries(users.map((u) => [u.id, u])), [users]);

  // Earliest pending-step due time, used to sort closest-to-breach first.
  function dueFor(b: any): number {
    for (const s of chains[b.id] ?? []) {
      if ((s.status ?? '').toLowerCase() === 'pending' && s.dueAt) return new Date(s.dueAt).getTime();
    }
    return Infinity;
  }
  const sorted = useMemo(() => [...rows].sort((a, b) => dueFor(a) - dueFor(b)), [rows, chains]);

  const stats = useMemo(() => {
    const now = new Date();
    const todayStr = now.toDateString();
    const weekAgo = new Date(now.getTime() - 7 * 86400000);
    let chained = 0, today = 0, week = 0;
    for (const b of rows) {
      if ((chains[b.id] ?? []).length > 0) chained++;
      const start = new Date(b.startTime);
      if (start.toDateString() === todayStr) today++;
      if (start >= weekAgo) week++;
    }
    return { pending: rows.length, chained, today, week };
  }, [rows, chains]);

  function currentStep(id: string): number {
    const steps = chains[id] ?? [];
    for (let i = 0; i < steps.length; i++) if ((steps[i].status ?? '').toLowerCase() === 'pending') return i + 1;
    return steps.length;
  }

  async function onApprove(b: any) {
    setBusyId(b.id);
    try {
      await api.approveBooking(b.id, '');
      // If chain → reload to show progress; if single-level → drop the row.
      if ((chains[b.id] ?? []).length > 0) await load();
      else setRows((r) => r.filter((x) => x.id !== b.id));
    } catch (e: any) { toast.error(t('approvals.approvalFailed'), e.displayMessage); }
    finally { setBusyId(null); }
  }

  async function confirmReject() {
    if (!rejecting || !rejectReason.trim()) return;
    setBusyId(rejecting.id);
    try {
      await api.rejectBooking(rejecting.id, rejectReason);
      setRows((r) => r.filter((x) => x.id !== rejecting.id));
      setRejecting(null); setRejectReason('');
    } catch (e: any) { toast.error(t('approvals.rejectFailed'), e.displayMessage); }
    finally { setBusyId(null); }
  }

  async function confirmDelegate() {
    if (!delegating || !delegateTo) return;
    setBusyId(delegating.id);
    try {
      await api.delegateBooking(delegating.id, delegateTo, delegateReason);
      setDelegating(null); setDelegateTo(''); setDelegateReason('');
      await load();
    } catch (e: any) { toast.error(t('approvals.delegateFailed'), e.displayMessage); }
    finally { setBusyId(null); }
  }

  return (
    <div>
      <div className="page-header">
        <div>
          <h1>{t('approvals.title')}</h1>
          <p className="muted">{t('approvals.pendingDecision')}</p>
        </div>
        <button className="btn-fsd ghost" onClick={load}><RefreshCcw size={14}/> {t('common.refresh')}</button>
      </div>

      {!loading && rows.length > 0 && (
        <div className="stat-strip">
          <div className="stat"><small>{t('approvals.statPending')}</small><b>{stats.pending}</b></div>
          <div className="stat"><small>{t('approvals.statChains')}</small><b>{stats.chained}</b></div>
          <div className="stat"><small>{t('common.today')}</small><b>{stats.today}</b></div>
          <div className="stat"><small>{t('approvals.statThisWeek')}</small><b>{stats.week}</b></div>
        </div>
      )}

      {loading && <p className="muted">{t('common.loading')}</p>}
      {!loading && rows.length === 0 && <p className="muted">{t('approvals.nonePending')}</p>}

      {sorted.map((b) => {
        const steps = chains[b.id] ?? [];
        const r = resourceMap[b.resourceId];
        const u = userMap[b.userId];
        return (
          <article key={b.id} className="fsd-card approval-card">
            <div className="thumb"><Clock size={18} color="white"/></div>
            <div className="approval-info">
              <div className="row gap-sm" style={{ alignItems: 'baseline' }}>
                <h3 className="truncate">{r?.name || b.resourceId}</h3>
                <span className="tag warning">{b.status}</span>
                {steps.length > 0 && (
                  <span className="tag info">
                    <GitBranch size={11}/> {t('approvals.chainStep', { current: currentStep(b.id), total: steps.length })}
                  </span>
                )}
              </div>
              <div className="muted text-sm row gap-sm" style={{ flexWrap: 'wrap' }}>
                <span><CalendarDays size={11}/> {new Date(b.startTime).toLocaleDateString()}</span>
                <span><Clock size={11}/> {new Date(b.startTime).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })} – {new Date(b.endTime).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</span>
                <span><User size={11}/> {u?.username || b.userId}</span>
              </div>
              {steps.length > 0 && <div style={{ marginTop: 8 }}><ApprovalTimeline steps={steps} submittedAt={b.createdAt}/></div>}
            </div>
            <div className="row gap-sm approval-actions">
              <button className="btn-fsd ghost" disabled={busyId === b.id}
                      onClick={() => { setDelegating(b); setDelegateTo(''); setDelegateReason(''); }}>
                <UserCog size={13}/> {t('approvals.delegate')}
              </button>
              <button className="btn-fsd danger" disabled={busyId === b.id}
                      onClick={() => { setRejecting(b); setRejectReason(''); }}>
                <X size={13}/> {t('approvals.reject')}
              </button>
              <button className="btn-fsd" style={{ background: 'var(--fsd-success)', borderColor: 'var(--fsd-success)' }}
                      disabled={busyId === b.id} onClick={() => onApprove(b)}>
                <Check size={13}/> {t('approvals.approve')}
              </button>
            </div>
          </article>
        );
      })}

      {rejecting && (
        <Modal title={t('approvals.rejectBooking')} onClose={() => setRejecting(null)} footer={<>
          <button className="btn-fsd ghost" onClick={() => setRejecting(null)}>{t('common.cancel')}</button>
          <button className="btn-fsd danger" disabled={!rejectReason.trim()} onClick={confirmReject}>
            <X size={13}/> {t('approvals.reject')}
          </button>
        </>}>
          <p className="muted text-sm">{t('approvals.reasonRequired')}</p>
          <label>{t('approvals.reason')}
            <textarea rows={3} value={rejectReason} onChange={(e) => setRejectReason(e.target.value)}
                      placeholder="e.g. Room reserved for board meeting"/>
          </label>
        </Modal>
      )}

      {delegating && (
        <Modal title={t('approvals.delegateApproval')} onClose={() => setDelegating(null)} footer={<>
          <button className="btn-fsd ghost" onClick={() => setDelegating(null)}>{t('common.cancel')}</button>
          <button className="btn-fsd" disabled={!delegateTo} onClick={confirmDelegate}>
            <UserCog size={13}/> {t('approvals.delegate')}
          </button>
        </>}>
          <p className="muted text-sm">{t('approvals.delegateHelp')}</p>
          <label>{t('approvals.delegateTo')}
            <select value={delegateTo} onChange={(e) => setDelegateTo(e.target.value)}>
              <option value="">{t('approvals.selectApprover')}</option>
              {users.map((u) => (
                <option key={u.id} value={u.id}>{u.username}{u.role ? ` — ${u.role}` : ''}</option>
              ))}
            </select>
          </label>
          <label>{t('approvals.reasonOptional')}
            <textarea rows={2} value={delegateReason} onChange={(e) => setDelegateReason(e.target.value)}
                      placeholder="e.g. On leave — please cover"/>
          </label>
        </Modal>
      )}
    </div>
  );
}
